import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { furnitureDesignContractHash, validateFurnitureDesignContract, validateVisualDesignContract } from "../../js/src/architecture/index.ts";
import { resolveBlender } from "./blender-toolchain.mjs";

const args=process.argv.slice(2),at=(flag:string)=>{const i=args.indexOf(flag);if(i<0||!args[i+1])throw new Error("usage: bun tools/architecture/build-furniture-contract.ts --contract <json> --visual <json> --out <glb> --blend-out <blend> --evidence <json>");return resolve(args[i+1])};
const contractPath=at("--contract"),visualPath=at("--visual"),out=at("--out"),blendOut=at("--blend-out"),evidencePath=at("--evidence"),toolchain=resolveBlender();
const visual=validateVisualDesignContract(JSON.parse(await readFile(visualPath,"utf8"))),contract=validateFurnitureDesignContract(JSON.parse(await readFile(contractPath,"utf8")),visual),contractHash=furnitureDesignContractHash(contract);
await Promise.all([mkdir(dirname(out),{recursive:true}),mkdir(dirname(blendOut),{recursive:true}),mkdir(dirname(evidencePath),{recursive:true})]);
const adapterPath=new URL("../blender/furniture-contract-adapter.py",import.meta.url).pathname,validatorPath=new URL("../blender/validate-furniture-contract-blend.py",import.meta.url).pathname;
const run=Bun.spawnSync([toolchain.binary,"--background","--factory-startup","--python",adapterPath,"--","--input",contractPath,"--contract-hash",contractHash,"--out",out,"--blend-out",blendOut],{stdout:"pipe",stderr:"pipe"});
if(run.exitCode!==0)throw new Error(`furniture Blender adapter failed (${run.exitCode})\n${run.stdout.toString()}\n${run.stderr.toString()}`);
const adapterLine=run.stdout.toString().split("\n").find(line=>line.startsWith("LIMINA_FURNITURE_OUTPUT="));if(!adapterLine)throw new Error(`furniture Blender adapter did not attest completion\n${run.stdout.toString()}\n${run.stderr.toString()}`);const adapterOutput=JSON.parse(adapterLine.slice(adapterLine.indexOf("=")+1));
const validation=Bun.spawnSync([toolchain.binary,"--background",blendOut,"--python",validatorPath,"--","--contract",contractPath,"--contract-hash",contractHash],{stdout:"pipe",stderr:"pipe"});
if(validation.exitCode!==0)throw new Error(`furniture source validation failed (${validation.exitCode})\n${validation.stdout.toString()}\n${validation.stderr.toString()}`);
const hash=(bytes:Uint8Array)=>`sha256:${createHash("sha256").update(bytes).digest("hex")}`,glb=await readFile(out),blend=await readFile(blendOut),adapter=await readFile(adapterPath),validator=await readFile(validatorPath);
function parseGlb(bytes:Buffer){if(bytes.toString("ascii",0,4)!=="glTF"||bytes.readUInt32LE(4)!==2||bytes.readUInt32LE(8)!==bytes.length)throw new Error("invalid GLB envelope");let offset=12,document:any;while(offset<bytes.length){const length=bytes.readUInt32LE(offset),kind=bytes.readUInt32LE(offset+4);offset+=8;if(kind===0x4e4f534a)document=JSON.parse(bytes.subarray(offset,offset+length).toString("utf8").trim());offset+=length}if(!document)throw new Error("GLB JSON missing");return document}
const document=parseGlb(glb),extras=document.asset?.extras;
if(extras?.liminaFurnitureContractHash!==contractHash||extras?.liminaVisualDesignHash!==contract.visualDesign.hash)throw new Error("exported GLB identity drifted");
if(extras?.liminaFurnitureContract?.id!==contract.id||extras?.liminaMaterialSources?.packs?.[0]?.provider!=="Poly Haven")throw new Error("exported GLB provenance missing");
for(const accessor of document.accessors??[])for(const field of [accessor.min,accessor.max])if(field?.some((v:unknown)=>typeof v!=="number"||!Number.isFinite(v)))throw new Error("exported GLB has non-finite accessor bounds");
const nodeIds=new Set((document.nodes??[]).map((node:any)=>node.extras?.["limina.id"]).filter(Boolean)),expectedIds=new Set([contract.id,...contract.parts.map(p=>p.id),...contract.sockets.map(s=>s.id),...contract.colliders.map(c=>c.id)]);
if(nodeIds.size!==expectedIds.size||[...expectedIds].some(id=>!nodeIds.has(id)))throw new Error("exported GLB semantic inventory drifted");
const identity=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],mul=(a:number[],b:number[])=>{const r=Array(16).fill(0);for(let c=0;c<4;c++)for(let row=0;row<4;row++)for(let k=0;k<4;k++)r[c*4+row]+=a[k*4+row]*b[c*4+k];return r},local=(node:any)=>{if(node.matrix)return node.matrix;const [x,y,z,w]=node.rotation??[0,0,0,1],[sx,sy,sz]=node.scale??[1,1,1],[tx,ty,tz]=node.translation??[0,0,0],xx=x*x,yy=y*y,zz=z*z,xy=x*y,xz=x*z,yz=y*z,wx=w*x,wy=w*y,wz=w*z;return[(1-2*(yy+zz))*sx,(2*(xy+wz))*sx,(2*(xz-wy))*sx,0,(2*(xy-wz))*sy,(1-2*(xx+zz))*sy,(2*(yz+wx))*sy,0,(2*(xz+wy))*sz,(2*(yz-wx))*sz,(1-2*(xx+yy))*sz,0,tx,ty,tz,1]},transform=(m:number[],p:number[])=>[m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]];
const parents=new Map<number,number>();for(let i=0;i<(document.nodes?.length??0);i++)for(const child of document.nodes[i].children??[])parents.set(child,i);const memo=new Map<number,number[]>(),world=(i:number):number[]=>{if(memo.has(i))return memo.get(i)!;const own=local(document.nodes[i]),value=parents.has(i)?mul(world(parents.get(i)!),own):mul(identity(),own);memo.set(i,value);return value};
const glbMin=[Infinity,Infinity,Infinity],glbMax=[-Infinity,-Infinity,-Infinity];for(let i=0;i<(document.nodes?.length??0);i++){const node=document.nodes[i];if(node.mesh===undefined)continue;for(const primitive of document.meshes[node.mesh].primitives??[]){const accessor=document.accessors[primitive.attributes.POSITION];if(!accessor?.min||!accessor?.max)throw new Error("mesh POSITION accessor lacks bounds");for(const x of[accessor.min[0],accessor.max[0]])for(const y of[accessor.min[1],accessor.max[1]])for(const z of[accessor.min[2],accessor.max[2]]){const p=transform(world(i),[x,y,z]);for(let axis=0;axis<3;axis++){glbMin[axis]=Math.min(glbMin[axis],p[axis]);glbMax[axis]=Math.max(glbMax[axis],p[axis])}}}}
if(glbMin.some(v=>!Number.isFinite(v))||glbMax.some(v=>!Number.isFinite(v)))throw new Error("exported GLB bounds are invalid");const glbBounds={min:glbMin,max:glbMax};
const blendValidationLine=validation.stdout.toString().split("\n").find(line=>line.startsWith("LIMINA_FURNITURE_BLEND_VALIDATION="));if(!blendValidationLine)throw new Error("fresh-process validator produced no evidence");
const evidence={schema:"limina.furniture-contract-build-evidence/v1",id:contract.id.split("/").slice(-2).join("-"),kind:contract.role,payloadHash:contractHash,sourceSpecHash:contract.visualDesign.hash,sourceIrHash:contractHash,primitiveCount:contract.parts.length,bounds:glbBounds,authoringBounds:adapterOutput.bounds,contract:{path:contractPath,hash:contractHash,visualDesignHash:contract.visualDesign.hash},toolchain,adapter:{path:adapterPath,sha256:hash(adapter)},validator:{path:validatorPath,sha256:hash(validator)},sourceBlend:{path:blendOut,sha256:hash(blend),bytes:blend.length},asset:{path:out,sha256:hash(glb),bytes:glb.length},inventory:{parts:contract.parts.length,joints:contract.joints.length,sockets:contract.sockets.length,occupancySockets:contract.sockets.filter(s=>s.kind==="occupancy").length,colliders:contract.colliders.length,materialRoles:contract.materialRoles},freshProcessValidation:JSON.parse(blendValidationLine.slice(blendValidationLine.indexOf("=")+1)),glbValidation:{version:document.asset.version,generator:document.asset.generator,nodes:document.nodes?.length??0,meshes:document.meshes?.length??0,materials:document.materials?.length??0,semanticIds:nodeIds.size,finiteAccessorBounds:true,contractIdentity:true,materialProvenance:true,boundsSource:"exported-glb-scene-graph"},rendered:false,gpuUsed:false,status:"cpu-authored-unreviewed"};
await writeFile(evidencePath,JSON.stringify(evidence,null,2)+"\n",{mode:0o600});console.log(JSON.stringify(evidence,null,2));
