import assert from"node:assert/strict";import{readFile}from"node:fs/promises";
const c=JSON.parse(await readFile(new URL("../../assets/buildings/authoring/furniture/hearth-settle-v2/design-contract.json",import.meta.url),"utf8")),parts=new Map(c.parts.map(p=>[p.id,p])),near=(actual,expected,tolerance,label)=>assert.ok(Math.abs(actual-expected)<=tolerance,`${label}: ${actual} != ${expected} ± ${tolerance}`);
assert.equal(c.id,"furniture/hearth-settle/v2");near(c.dimensions.widthM,2.16,.001,"width");near(c.dimensions.heightM,1.28,.001,"height");assert.ok(c.dimensions.widthM/c.dimensions.heightM>=1.65&&c.dimensions.widthM/c.dimensions.heightM<=1.72);
const seat=parts.get("seat/plank");assert.ok(seat);assert.equal(c.parts.filter(p=>p.id.startsWith("seat/")).length,1,"seat must be one continuous plank");near(seat.geometry.size[0],1.82,.001,"seat width");near(seat.geometry.size[2],.50,.001,"seat depth");near(seat.center[1]+seat.geometry.size[1]/2,.46,.001,"seat top");assert.deepEqual(seat.rotationDeg,[0,0,0]);
for(const side of["left","right"]){assert.deepEqual(parts.get(`leg/rear-${side}`).rotationDeg,[0,0,0],"lower rear legs must be plumb");assert.deepEqual(parts.get(`back-post/${side}`).rotationDeg,[4,0,0],"upper back post rake");}
const lineZ=y=>.185+Math.tan(4*Math.PI/180)*(y-.430);for(const p of c.parts.filter(p=>p.id.startsWith("back-post/")||p.id.startsWith("rail/back-")||p.id.startsWith("stile/")||p.id.startsWith("panel/")||p.id==="crest")){near(p.center[2],lineZ(p.center[1]),.000001,`${p.id} common rake plane`);assert.deepEqual(p.rotationDeg,[4,0,0],`${p.id} common rake angle`)}
for(const socket of c.sockets.filter(s=>s.kind==="occupancy")){assert.deepEqual(socket.facing,[0,0,-1]);assert.equal(socket.supportedBy,"seat/plank")}assert.deepEqual(c.sockets.find(s=>s.id==="approach/left").facing,[0,0,1]);
assert.equal(c.parts.filter(p=>p.kind==="panel").length,4);assert.ok(c.parts.filter(p=>p.kind==="peg").length>=8);assert.equal(c.colliders.length,7);
console.log("hearth settle v2 section checks passed: plumb lower legs, coherent +4° upper frame, one 1.82x0.50m seat");
