// Phase 9 — the terrain.* / world.* skill seam. Four Zod-typed, permissioned,
// traced skills closing over a pluggable TerrainSource (the procedural source
// offline/in tests; the learned model at authoring; the tile cache at replay)
// and a content-addressed TileCache.
//
// THE RECORD/REPLAY SPINE (same shape as Phase 8, one level up): world.
// generateRegion is a SKILL, so the world log records its REQUEST ({seed, bounds,
// lod, hints}) as a single SKILL command. The op_physics_add_heightfield calls it
// makes are NESTED (depth > 0) and are therefore NOT separately logged — replay
// RE-INVOKES generateRegion, which re-resolves the SAME deterministic tiles from
// the source/cache and re-applies the SAME heightfield colliders in the SAME
// order, allocating the SAME body ids. The log carries the request + a content
// hash; the tile BYTES ride the cache/export, never the log.
//
// OFF-LOOP NOTE: the heavy generate is meant to run off the frame loop (the
// action queue marshals the request to the generator worker and applies tiles
// between frames). For this headless cut the apply is SYNCHRONOUS, but the skill
// is shaped for the off-loop wrapper: it returns a region HANDLE (regionId) and
// emits `terrain.tile.ready` per applied tile, so an async marshaller can later
// stream the same events without changing the contract.

import { z } from "../../build/zod.bundle.mjs";
import { MAX_ENTITIES, despawnRenderable, spawnRenderable } from "../ecs/world.ts";
import type { Transformable } from "../ecs/world.ts";
import type { TerrainSource, TerrainTile, TileRequest } from "../terrain/types.ts";
import { TILE_SIZE } from "../terrain/procedural.ts";
import { TERRAIN_TYPE_NAMES, terrainTypeHints, type RegionBounds, type TerrainTypeName } from "../terrain/terrain-types.ts";
import { requestKey, tileContentHash, TileCache } from "../terrain/tilecache.ts";
import { buildTerrainMesh, disposeTerrainMesh, type TerrainMeshOptions } from "../terrain/render.ts";
import { scatterBiomeContent } from "../terrain/biome-content.ts";
import type { InvokeBase, SkillDefinition, SkillRegistry } from "./registry.ts";

const Vec3 = z.tuple([z.number(), z.number(), z.number()]);

/** Inert transform binding for a static terrain tile (the render mesh is attached
 *  by the host's render path — Workstream D / UAT; the ECS entity exists headless
 *  so the tile is a first-class, snapshot/replay-comparable entity). */
function inertTransform(): Transformable {
  return { position: { set() {} }, quaternion: { set() {} }, scale: { set() {} } };
}

/** Per-region state: which tiles are currently applied (for streamFollow load/
 *  unload bookkeeping). Lives in the closure of one registry, so a fresh replay
 *  registry starts empty and rebuilds it by re-invoking the recorded skills. */
export interface AppliedTile {
  bodyId: number;
  entity: string;
  eid: number;
  tx: number;
  tz: number;
  /** The render-only visible terrain mesh mounted on this tile by the AUTO-SURFACE
   *  (world.generateRegion `render`), if any. A THREE.Mesh; held loosely so the type
   *  doesn't leak THREE into the (headless) skill contract. Removed/disposed when the
   *  tile is streamed out. Absent when the region was generated with `render:false`. */
  mesh?: unknown;
}
/** Live state of a generated region (the tiles actually applied). Exported so
 *  asset.scatter can bind a scatter to the SAME region world.generateRegion built —
 *  it reads the region's seed/lod + applied tile coords, never a free-floating seed. */
export interface RegionState {
  seed: number;
  lod: number;
  hints?: Record<string, number>;
  tiles: Map<string, AppliedTile>;
  /** The terrain TYPE the region was generated with (when one was passed). Lets
   *  world.populateBiome resolve the type's content layers from the region alone. */
  type?: TerrainTypeName;
  /** The resolved render-only surface options the AUTO-SURFACE builds each tile mesh
   *  with (region-wide: the elevation bands resolve against ONE surveyed relief, so
   *  every tile — and any later streamed-in tile — bands consistently). Undefined when
   *  the region was generated with `render:false` (colliders/data only, no visible mesh). */
  meshOpts?: TerrainMeshOptions;
}

/** A stable region handle derived from the request (deterministic across runs). */
function regionIdOf(seed: number, lod: number, b: { minTx: number; minTz: number; maxTx: number; maxTz: number }): string {
  return `rgn_${seed | 0}_l${lod | 0}_${b.minTx}_${b.minTz}_${b.maxTx}_${b.maxTz}`;
}

// ───────────────────────── AUTO-SURFACE (render-only) ─────────────────────────
// world.generateRegion builds the heightfield COLLIDERS (the sim truth) AND, by
// default, the VISIBLE PBR terrain mesh per tile — so a region generated by the skill
// ALONE renders a gorgeous textured landscape, not an invisible collider. RENDER-ONLY:
// the meshes are plain scene objects (never ECS entities, never the world log); replay
// rebuilds them from the same deterministic tiles exactly as it rebuilds the colliders.
// Opt out with `render:false` (colliders/data only — e.g. a headless collider test).

/** The opt-in surface RECIPE for the auto-surface (recorded verbatim in the log; render-
 *  only). When omitted the default is the procedural-PBR surface derived from the surveyed
 *  relief, so a bare generateRegion still renders a textured world. Every field maps onto
 *  TerrainMeshOptions (terrain/render.ts) — a demo passes its EXACT params so its look is
 *  byte-identical to the hand-rolled tile-loop it replaces. */
const surfaceSchema = z.object({
  /** "pbr" (default) = procedural-PBR (triplanar layers + detail normals + honest
   *  roughness). "palette" = the flat elevation+biome colour ramp. "shoreline" = a flat
   *  sand colour with the tropical wet/foam waterline band. "flat" = a plain matte colour. */
  mode: z.enum(["pbr", "palette", "shoreline", "flat"]).optional(),
  color: z.number().int().min(0).max(0xffffff).optional(),
  roughness: z.number().min(0).max(1).optional(),
  metalness: z.number().min(0).max(1).optional(),
  doubleSide: z.boolean().optional(),
  /** Sea-level world Y the bands centre on. Omit → derived from the relief + `seaFraction`. */
  seaLevel: z.number().optional(),
  /** Fraction [0,1] of the surveyed relief the sea floods, when `seaLevel` is omitted.
   *  Default 0 (seaLevel = relief.minY). */
  seaFraction: z.number().min(0).max(1).optional(),
  /** Relief override the elevation bands normalise against. Omit → the surveyed region relief. */
  minY: z.number().optional(),
  maxY: z.number().optional(),
  /** OPT-IN wet-shore band for the "pbr" surface (texture-terminates the waterline). */
  waterline: z.object({
    seaLevel: z.number().optional(),
    wetBand: z.number().optional(),
    foamBand: z.number().optional(),
    darken: z.number().optional(),
    wetRoughness: z.number().optional(),
    foam: z.number().optional(),
    foamColor: z.number().int().optional(),
  }).optional(),
  /** Tropical shoreline band overrides for the "shoreline" surface. */
  shoreline: z.object({
    seaLevel: z.number().optional(),
    foamColor: z.number().int().optional(),
    wetColor: z.number().int().optional(),
    wetBand: z.number().optional(),
    foamBand: z.number().optional(),
  }).optional(),
  /** Render-only vertical exaggeration of the rendered geometry (collider untouched). */
  exaggerateY: z.object({ factor: z.number(), pivot: z.number() }).optional(),
});
type SurfaceInput = z.infer<typeof surfaceSchema>;

/** The surveyed world-Y relief of a region (the bands' normalisation range). */
interface Relief { minY: number; maxY: number }

/** World-Y extent of one tile (origin.y + h·scaleY over its raw heights). Used to band the
 *  visible mesh (render-only). NOTE: this is a SEPARATE relief from the one biome-content's
 *  `surveyRegionRelief` computes for scatter gating (which samples the surface on a finer
 *  grid). They agree closely; authors deriving a waterLevel for world.populateBiome should
 *  use the scatter survey (surveyRegionRelief) — not this mesh-banding extent — as the
 *  source of truth for placement gates. (Follow-up: unify if they ever diverge materially.) */
function tileWorldYExtent(tile: TerrainTile): Relief {
  const oy = tile.origin[1], sy = tile.scale[1];
  let lo = Infinity, hi = -Infinity;
  for (let i = 0; i < tile.heights.length; i++) { const h = tile.heights[i]; if (h < lo) lo = h; if (h > hi) hi = h; }
  return { minY: oy + lo * sy, maxY: oy + hi * sy };
}

/** Resolve the surface recipe + surveyed relief into the concrete TerrainMeshOptions
 *  every tile mesh is built with. Pure; the same recipe + relief always yields the same
 *  options, so the auto-surface is deterministic (render-only). Also returns the derived
 *  sea level (for the skill output). */
function resolveSurfaceMeshOpts(surface: SurfaceInput | undefined, relief: Relief): { opts: TerrainMeshOptions; seaLevel: number } {
  const mode = surface?.mode ?? "pbr";
  const minY = surface?.minY ?? relief.minY;
  const maxY = surface?.maxY ?? relief.maxY;
  const seaLevel = surface?.seaLevel ?? (minY + (surface?.seaFraction ?? 0) * (maxY - minY));
  const opts: TerrainMeshOptions = {};
  if (surface?.color !== undefined) opts.color = surface.color;
  if (surface?.roughness !== undefined) opts.roughness = surface.roughness;
  if (surface?.metalness !== undefined) opts.metalness = surface.metalness;
  if (surface?.doubleSide === true) opts.doubleSide = true;
  const band = { seaLevel, minY, maxY };
  if (mode === "pbr") opts.pbr = surface?.waterline !== undefined ? { ...band, waterline: surface.waterline } : band;
  else if (mode === "palette") opts.palette = band;
  else if (mode === "shoreline") opts.shoreline = { ...(surface?.shoreline ?? {}), seaLevel: surface?.shoreline?.seaLevel ?? seaLevel };
  // mode "flat": plain colour/roughness only (no banded surface node).
  if (surface?.exaggerateY !== undefined) opts.exaggerateY = surface.exaggerateY;
  return { opts, seaLevel };
}

/** Minimal scene surface the auto-surface mounts onto (THREE.Scene / a headless stub). */
interface SceneAdd { add(child: unknown): void; remove(child: unknown): void }

/** Build + mount the visible terrain mesh for one applied tile (render-only). No-op when
 *  the region isn't rendering (`meshOpts` unset), the tile is already mounted, or the
 *  scene can't take children (a headless context with no scene.add). Stores the mesh on
 *  the AppliedTile so streamFollow/teardown can remove + dispose it. */
function mountTileMesh(region: RegionState, tile: TerrainTile, applied: AppliedTile, scene: unknown): void {
  if (region.meshOpts === undefined || applied.mesh !== undefined) return;
  const s = scene as SceneAdd | undefined;
  if (s === undefined || typeof s.add !== "function") return;
  const mesh = buildTerrainMesh(tile, region.meshOpts);
  s.add(mesh);
  applied.mesh = mesh;
}

/** Remove + dispose an applied tile's visible mesh (streamFollow unload / teardown). */
function unmountTileMesh(applied: AppliedTile, scene: unknown): void {
  if (applied.mesh === undefined) return;
  const s = scene as SceneAdd | undefined;
  if (s !== undefined && typeof s.remove === "function") s.remove(applied.mesh);
  disposeTerrainMesh(applied.mesh as Parameters<typeof disposeTerrainMesh>[0]);
  applied.mesh = undefined;
}

/** Register the terrain.* / world.* skills bound to a source + cache. The default
 *  core wiring passes a ProceduralTerrainSource; a runtime can pass the cached
 *  source (replay) or the model-backed source (authoring) instead. */
export function registerTerrainSkills(
  registry: SkillRegistry,
  source: TerrainSource,
  cache: TileCache = new TileCache(),
  regions: Map<string, RegionState> = new Map(),
): { cache: TileCache; regions: Map<string, RegionState> } {

  /** Resolve + apply one tile: build the native heightfield collider, register a
   *  terrain entity, record it in the region, and emit terrain.tile.ready. */
  async function applyTile(
    region: RegionState,
    regionId: string,
    tx: number,
    tz: number,
    ctx: Parameters<SkillDefinition["handler"]>[1],
  ): Promise<{ key: string; bodyId: number; entity: string; applied: AppliedTile; tile?: TerrainTile }> {
    const req: TileRequest = { seed: region.seed, tx, tz, lod: region.lod, hints: region.hints };
    const key = requestKey(req);
    const existing = region.tiles.get(key);
    if (existing !== undefined) return { key, bodyId: existing.bodyId, entity: existing.entity, applied: existing };
    const tile = await cache.resolve(req, source);
    const [ox, oy, oz] = tile.origin;
    const [sx, sy, sz] = tile.scale;
    const bodyId = ctx.world.ops.op_physics_add_heightfield(ox, oy, oz, tile.nrows, tile.ncols, sx, sy, sz, tile.heights);
    const eid = spawnRenderable(ctx.world.ecs, inertTransform(), ox, oy, oz);
    if (eid >= MAX_ENTITIES) {
      despawnRenderable(ctx.world.ecs, eid);
      ctx.world.ops.op_physics_remove_body(bodyId);
      throw new Error("terrain: entity capacity exceeded (MAX_ENTITIES)");
    }
    const entity = ctx.world.entities.create({ eid, bodyId });
    const applied: AppliedTile = { bodyId, entity, eid, tx, tz };
    region.tiles.set(key, applied);
    ctx.emit("terrain.tile.ready", {
      regionId, tx, tz, key, hash: tileContentHash(tile), bodyId, entity,
      origin: tile.origin, source: source.name,
    });
    return { key, bodyId, entity, applied, tile };
  }

  // ---- world.generateRegion ------------------------------------------------
  const boundsSchema = z.object({
    minTx: z.number().int(),
    minTz: z.number().int(),
    maxTx: z.number().int(),
    maxTz: z.number().int(),
  }).refine((b) => b.maxTx >= b.minTx && b.maxTz >= b.minTz, "bounds max must be >= min")
    .refine((b) => (b.maxTx - b.minTx + 1) * (b.maxTz - b.minTz + 1) <= 256, "region too large (>256 tiles)");
  const generateRegionInput = z.object({
    seed: z.number().int(),
    bounds: boundsSchema,
    lod: z.number().int().min(0).max(4).default(0),
    // AGENT-NATIVE SEEDING: pick a named terrain TYPE ("beach", "mountains", "desert", …)
    // and it resolves to the full shaping+climate config for the region (the deterministic
    // generator builds that world). Mutually composable with raw `hints` (explicit hints
    // override the type's resolved knobs); omit both for the byte-identical default field.
    type: z.enum(TERRAIN_TYPE_NAMES as [string, ...string[]]).optional(),
    hints: z.record(z.string(), z.number()).optional(),
    // AUTO-SURFACE (render-only; default ON): after building the colliders, build + add the
    // VISIBLE PBR terrain mesh per tile so the region renders by default. Opt out with
    // `render:false` (colliders/data only). `surface` tunes the look (defaults to procedural
    // PBR derived from the surveyed relief). RENDER-ONLY: never the sim/log/replay — replay
    // rebuilds the meshes from the same deterministic tiles, exactly like the colliders.
    render: z.boolean().default(true),
    surface: surfaceSchema.optional(),
  });
  const generateRegionOutput = z.object({
    regionId: z.string(),
    tiles: z.number().int(),
    bodies: z.array(z.number().int()),
    keys: z.array(z.string()),
    /** Number of visible terrain meshes the auto-surface mounted (0 when render:false or
     *  the context has no scene). Render-only — not part of the sim/log. */
    meshes: z.number().int(),
    /** The surveyed world-Y relief the surface bands resolved against (when rendering). */
    relief: z.object({ minY: z.number(), maxY: z.number() }).optional(),
    /** The sea level the surface used (explicit or derived from the relief). */
    seaLevel: z.number().optional(),
  });
  const generateRegion: SkillDefinition<z.infer<typeof generateRegionInput>, z.infer<typeof generateRegionOutput>> = {
    name: "world.generateRegion",
    version: "1.0.0",
    description: "Generate a rectangular region of terrain: build the heightfield COLLIDERS from a deterministic source AND (by default) the VISIBLE procedural-PBR terrain mesh per tile, so the region renders a textured landscape out of the box. High-cost; streams tiles, emitting terrain.tile.ready per tile. Returns a region handle + the surveyed relief/seaLevel. The world log records this REQUEST; the tile bytes ride the cache/export; the visible meshes are RENDER-ONLY (rebuilt from the same tiles on replay). Opt out of the mesh with render:false (colliders/data only); tune the look with `surface`.",
    category: "world",
    permissions: ["terrain.generate"],
    input: generateRegionInput,
    output: generateRegionOutput,
    handler: async (input, ctx) => {
      // Resolve a named terrain TYPE into the full shaping+climate hint map, then let any
      // explicit `hints` override individual knobs. Pure + deterministic, so replay (which
      // re-invokes this skill with the recorded request) re-derives the identical hints.
      const typed = input.type !== undefined ? terrainTypeHints(input.type as TerrainTypeName, input.bounds) : undefined;
      const merged = (typed !== undefined || input.hints !== undefined)
        ? { ...(typed ?? {}), ...(input.hints ?? {}) }
        : undefined;
      const regionId = regionIdOf(input.seed, input.lod, input.bounds);
      let region = regions.get(regionId);
      if (region === undefined) {
        region = { seed: input.seed, lod: input.lod, hints: merged, type: input.type as TerrainTypeName | undefined, tiles: new Map() };
        regions.set(regionId, region);
      } else if (region.type === undefined && input.type !== undefined) {
        region.type = input.type as TerrainTypeName;
      }
      const bodies: number[] = [];
      const keys: string[] = [];
      // Deterministic apply order (tz outer, tx inner) so body-id allocation is
      // reproducible on replay. Capture the resolved tiles for the auto-surface below.
      const applied: { applied: AppliedTile; tile?: TerrainTile }[] = [];
      for (let tz = input.bounds.minTz; tz <= input.bounds.maxTz; tz++) {
        for (let tx = input.bounds.minTx; tx <= input.bounds.maxTx; tx++) {
          const a = await applyTile(region, regionId, tx, tz, ctx);
          bodies.push(a.bodyId);
          keys.push(a.key);
          applied.push({ applied: a.applied, tile: a.tile });
        }
      }

      // ── AUTO-SURFACE (render-only, default ON) ───────────────────────────────────
      // Build the visible PBR terrain mesh per tile so the region is gorgeous out of the
      // box. The elevation bands resolve against ONE region-wide relief, surveyed from the
      // region's tiles (fresh ones in hand, else resolved from the cache — source-agnostic,
      // so it works under the cached replay source AND a RE-GEN of an already-cached region
      // never collapses to a degenerate 0..0 band). The resolved options are stored on the
      // region so any later streamed-in tile bands identically. NEVER touches the sim/log;
      // replay rebuilds it from the same tiles.
      let meshCount = 0;
      let reliefOut: Relief | undefined;
      let seaLevelOut: number | undefined;
      if (input.render !== false) {
        // Survey relief unless the caller pinned the full band (minY + maxY + seaLevel).
        let minY = input.surface?.minY;
        let maxY = input.surface?.maxY;
        if (minY === undefined || maxY === undefined || input.surface?.seaLevel === undefined) {
          let lo = Infinity, hi = -Infinity;
          for (const { applied: at, tile } of applied) {
            // Fresh tile in hand → use it; an already-cached tile (re-gen) → cheap cache hit,
            // so the band is ALWAYS real (never the degenerate 0..0 that would mis-colour a
            // later streamFollow tile banding against it).
            const t = tile ?? await cache.resolve({ seed: region.seed, tx: at.tx, tz: at.tz, lod: region.lod, hints: region.hints }, source);
            const e = tileWorldYExtent(t);
            if (e.minY < lo) lo = e.minY;
            if (e.maxY > hi) hi = e.maxY;
          }
          if (minY === undefined) minY = lo;
          if (maxY === undefined) maxY = hi;
        }
        const relief: Relief = { minY, maxY };
        const { opts, seaLevel } = resolveSurfaceMeshOpts(input.surface, relief);
        region.meshOpts = opts; // a REAL band on every (re-)gen — no degenerate overwrite
        reliefOut = relief;
        seaLevelOut = seaLevel;
        // Allocate + mount the VISIBLE meshes only on a world with a LIVE renderer (the
        // windowed/live path). A headless / replay / export world (no renderer) keeps the
        // colliders + the resolved meshOpts band but does NOT allocate discardable meshes
        // (scene.add is a no-op there, so the meshes would be orphaned + never disposed) —
        // determinism is unaffected (render-only) and the surface rebuilds on a live
        // re-attach/stream. A capturing test world opts in by setting a (stub) renderer.
        if (ctx.world.renderer !== undefined && ctx.world.renderer !== null) {
          for (const { applied: at, tile } of applied) {
            if (tile === undefined) continue; // already-mounted tile (re-gen): its mesh stands
            mountTileMesh(region, tile, at, ctx.world.scene);
            if (at.mesh !== undefined) meshCount++;
          }
        }
      } else {
        region.meshOpts = undefined;
      }

      ctx.emit("terrain.region.ready", { regionId, tiles: bodies.length, meshes: meshCount });
      return { regionId, tiles: bodies.length, bodies, keys, meshes: meshCount, relief: reliefOut, seaLevel: seaLevelOut };
    },
  };

  // ---- world.streamFollow --------------------------------------------------
  const streamFollowInput = z.object({
    regionId: z.string(),
    anchor: Vec3,
    radius: z.number().int().min(0).max(8).default(1),
  });
  const streamFollowOutput = z.object({
    regionId: z.string(),
    loaded: z.array(z.string()),
    removed: z.array(z.string()),
    active: z.number().int(),
  });
  const streamFollow: SkillDefinition<z.infer<typeof streamFollowInput>, z.infer<typeof streamFollowOutput>> = {
    name: "world.streamFollow",
    version: "1.0.0",
    description: "Stream terrain tiles in a square window around an anchor (agent/camera): generate+apply tiles entering the window, remove tiles leaving a keep-margin. Returns the loaded/removed tile keys. Off-loop in production; synchronous here.",
    category: "world",
    permissions: ["terrain.generate"],
    input: streamFollowInput,
    output: streamFollowOutput,
    handler: async (input, ctx) => {
      const region = regions.get(input.regionId);
      if (region === undefined) throw new Error(`world.streamFollow: unknown region ${input.regionId}`);
      const atx = Math.floor(input.anchor[0] / TILE_SIZE);
      const atz = Math.floor(input.anchor[2] / TILE_SIZE);
      const keep = input.radius + 1; // hysteresis: load within radius, drop beyond keep
      // Load tiles entering the window (deterministic order).
      const loaded: string[] = [];
      for (let tz = atz - input.radius; tz <= atz + input.radius; tz++) {
        for (let tx = atx - input.radius; tx <= atx + input.radius; tx++) {
          const req: TileRequest = { seed: region.seed, tx, tz, lod: region.lod, hints: region.hints };
          if (!region.tiles.has(requestKey(req))) {
            const a = await applyTile(region, input.regionId, tx, tz, ctx);
            // Mount the visible surface for the newly-streamed tile (render-only; no-op when
            // the region was generated with render:false). Uses the region-wide meshOpts so
            // a streamed-in tile bands consistently with the originally-generated ones. Gated
            // on a LIVE renderer (a headless/replay world keeps the band but allocates no
            // discardable mesh — same policy as world.generateRegion's auto-surface).
            if (a.tile !== undefined && ctx.world.renderer !== undefined && ctx.world.renderer !== null) {
              mountTileMesh(region, a.tile, a.applied, ctx.world.scene);
            }
            loaded.push(a.key);
          }
        }
      }
      // Remove tiles outside the keep-margin (and dispose their visible mesh).
      const removed: string[] = [];
      for (const [key, t] of [...region.tiles]) {
        if (Math.abs(t.tx - atx) > keep || Math.abs(t.tz - atz) > keep) {
          unmountTileMesh(t, ctx.world.scene);
          ctx.world.ops.op_physics_remove_body(t.bodyId);
          despawnRenderable(ctx.world.ecs, t.eid);
          ctx.world.entities.destroy(t.entity);
          region.tiles.delete(key);
          removed.push(key);
          ctx.emit("terrain.tile.unloaded", { regionId: input.regionId, key, tx: t.tx, tz: t.tz });
        }
      }
      return { regionId: input.regionId, loaded, removed, active: region.tiles.size };
    },
  };

  // ---- terrain.sampleHeight ------------------------------------------------
  const sampleHeightInput = z.object({
    seed: z.number().int(),
    x: z.number(),
    z: z.number(),
    lod: z.number().int().min(0).max(4).default(0),
  });
  const sampleHeight: SkillDefinition<z.infer<typeof sampleHeightInput>, { y: number }> = {
    name: "terrain.sampleHeight",
    version: "1.0.0",
    description: "O(1) deterministic surface-elevation query at a world (x,z) for a seed/lod (snapping/placement). Returns world Y.",
    category: "terrain",
    permissions: ["terrain.read"],
    input: sampleHeightInput,
    output: z.object({ y: z.number() }),
    handler: (input) => ({ y: source.sampleHeight(input.seed, input.x, input.z, input.lod) }),
  };

  // ---- terrain.sampleClimate -----------------------------------------------
  const sampleClimateInput = z.object({
    seed: z.number().int(),
    x: z.number(),
    z: z.number(),
    // SAME opt-in shaping (incl. per-type climate bias) a region was generated with, so
    // the perceived biome matches the shaped tiles; omit for the byte-identical base.
    hints: z.record(z.string(), z.number()).optional(),
  });
  const sampleClimate: SkillDefinition<z.infer<typeof sampleClimateInput>, { tempC: number; precipMm: number; biome: number }> = {
    name: "terrain.sampleClimate",
    version: "1.0.0",
    description: "Deterministic per-coordinate climate (tempC, precipMm, biome) for agent perception. Pass the region's terrain hints to read the per-type biome.",
    category: "terrain",
    permissions: ["terrain.read"],
    input: sampleClimateInput,
    output: z.object({ tempC: z.number(), precipMm: z.number(), biome: z.number().int() }),
    handler: (input) => source.sampleClimate(input.seed, input.x, input.z, input.hints),
  };

  // ---- world.populateBiome -------------------------------------------------
  // The first-class SKILL wrapper of scatterBiomeContent: scatter a terrain TYPE's
  // biome content (pines on mountain slopes, cacti in the desert, palms on the beach,
  // …) over an ALREADY-GENERATED region. Surveys the region's relief with the EXACT
  // hints it was generated with (the region-hints survey path — the "only rocks, no
  // pines" fix), resolves the type's content layers to concrete ScatterConfigs, and
  // drives asset.scatter once per layer.
  //
  // DETERMINISM / REPLAY: populateBiome orchestrates NESTED asset.scatter invokes. The
  // recorder records only the TOP-LEVEL call (it records at depth 0; the nested
  // asset.scatter invokes run at depth > 0 and are NOT separately recorded — no
  // double-record). On replay this skill is re-invoked and re-drives the SAME
  // asset.scatter calls deterministically (asset.scatter itself recomputes its placements
  // over the same baked/cached tiles), so the placement set is bit-identical.
  const populateBiomeInput = z.object({
    /** The region from world.generateRegion to populate (binds the scatter to its tiles). */
    regionId: z.string(),
    /** The terrain TYPE whose content layers to scatter. Defaults to the type the region
     *  was generated with (stored on the region); required if the region had no type. */
    type: z.enum(TERRAIN_TYPE_NAMES as [string, ...string[]]).optional(),
    /** Water level for waterGated layers (props on dry land only). Default: for a water/
     *  island type, the low 40% of the relief floods; otherwise none. */
    waterLevel: z.number().optional(),
    /** Dry margin (world Y) added ABOVE the water level for waterGated layers. Default 0. */
    waterMargin: z.number().optional(),
    /** Override the scatter seed (default: the region's generation seed). */
    seed: z.number().int().optional(),
  });
  const populateBiomeOutput = z.object({
    regionId: z.string(),
    type: z.string(),
    /** Total instances placed across all layers. */
    instances: z.number().int(),
    /** Surveyed relief the fractional elevation gates resolved against. */
    relief: z.object({ minY: z.number(), maxY: z.number() }),
    /** Per-layer summary (instances + mounted InstancedMesh count). */
    layers: z.array(z.object({ instances: z.number().int(), mounted: z.number().int() })),
  });
  const populateBiome: SkillDefinition<z.infer<typeof populateBiomeInput>, z.infer<typeof populateBiomeOutput>> = {
    name: "world.populateBiome",
    version: "1.0.0",
    description: "Scatter a terrain TYPE's biome content (trees/rocks/grass/cacti/palms, biome- and elevation-gated) over an ALREADY-GENERATED region (by regionId), via the deterministic asset.scatter seam. Surveys the region's relief with the hints it was generated with, resolves the type's content layers, and drives asset.scatter per layer. Deterministic + replay-safe: the world log records THIS request; the nested asset.scatter calls are recomputed on replay (no double-record). Returns the placement count + per-layer summary.",
    category: "world",
    permissions: ["scene.write"],
    input: populateBiomeInput,
    output: populateBiomeOutput,
    handler: async (input, ctx) => {
      const region = regions.get(input.regionId);
      if (region === undefined) {
        throw new Error(`world.populateBiome: unknown region '${input.regionId}' — generate it with world.generateRegion first`);
      }
      const type = (input.type as TerrainTypeName | undefined) ?? region.type;
      if (type === undefined) {
        throw new Error(`world.populateBiome: region '${input.regionId}' has no terrain type — pass an explicit \`type\``);
      }
      if (region.tiles.size === 0) {
        throw new Error(`world.populateBiome: region '${input.regionId}' has no applied tiles`);
      }
      // Derive the region's tile-grid bounds from its applied tiles (single source of truth).
      let minTx = Infinity, minTz = Infinity, maxTx = -Infinity, maxTz = -Infinity;
      for (const t of region.tiles.values()) {
        if (t.tx < minTx) minTx = t.tx;
        if (t.tx > maxTx) maxTx = t.tx;
        if (t.tz < minTz) minTz = t.tz;
        if (t.tz > maxTz) maxTz = t.tz;
      }
      const bounds: RegionBounds = { minTx, minTz, maxTx, maxTz };
      const seed = input.seed ?? region.seed;
      // Build the nested-invoke base from this skill's execution context (the SAME registry
      // the terrain skills were registered on — the recorder's patched invoke, so the nested
      // asset.scatter calls run at depth > 0 and are not separately recorded).
      const base: InvokeBase = {
        agentId: ctx.agentId, sessionId: ctx.sessionId, permissions: ctx.permissions, tick: ctx.tick, world: ctx.world,
      };
      const res = await scatterBiomeContent({
        registry, source, regions, regionId: input.regionId, type, bounds, seed, base,
        waterLevel: input.waterLevel, waterMargin: input.waterMargin,
      });
      ctx.emit("terrain.region.populated", {
        regionId: input.regionId, type, instances: res.instances, layers: res.layers.length,
      });
      return {
        regionId: input.regionId,
        type,
        instances: res.instances,
        relief: { minY: res.survey.minY, maxY: res.survey.maxY },
        layers: res.layers.map((l) => ({ instances: l.instances, mounted: l.mounted })),
      };
    },
  };

  registry.register(generateRegion);
  registry.register(streamFollow);
  registry.register(sampleHeight);
  registry.register(sampleClimate);
  registry.register(populateBiome);

  return { cache, regions };
}
