import fs from "node:fs";
import { compileArchitecture, type ArchitectureSpec } from "../src/architecture/index.ts";

const fail=(message:string):never=>{throw new Error(`p_architecture_volume FAIL: ${message}`);};
const assert=(value:unknown,message:string):asserts value=>{if(!value)fail(message);};
const source=new URL("../../assets/buildings/functional-hall-house-architecture-v1.json",import.meta.url),spec=JSON.parse(fs.readFileSync(source,"utf8")) as ArchitectureSpec;
const compiled=compileArchitecture(spec);
assert(compiled.volumes.length===2,"main hall and service bay are not distinct compiled volumes");
assert(compiled.walls.filter(wall=>/^(main-hall|service-bay)\/edge-/.test(wall.id)).length===8,"two rectangular volumes did not derive eight ordered wall edges");
assert(compiled.walls.some(wall=>wall.id==="dormer/south/front"),"dormer front did not compile as an opening-bearing structural wall");
assert(compiled.volumes.every(volume=>compiled.primitives.includes(volume.floor)&&compiled.primitives.includes(volume.ceiling)),"volume floor/ceiling slabs are absent from IR");
assert(compiled.walls.find(wall=>wall.id==="service-bay/edge-2")?.segments.length===0,"full-width hall/service passage was silently filled");
assert(compiled.walls.find(wall=>wall.id==="main-hall/edge-0")?.openingIds.join(",")==="window/south-west,portal/exterior,passage/service-bay","south facade opening order drifted");
assert(compiled.entrances[0]?.openingId==="portal/exterior","entrance is not tied to the derived portal void");
assert(compiled.doors.length===1&&compiled.doors[0].id==="door/front"&&compiled.doors[0].openYaw<-Math.PI/2,"functional door assembly or beyond-90-degree swing is missing");
assert(compiled.windows.length===6&&compiled.windows.every(window=>window.reveals.length===4&&window.frame.length===4&&window.mullions.length>=1&&window.came.length>=2),"volume and dormer windows lack complete opening assemblies");
assert(compiled.dormers.length===1&&compiled.dormers[0].windowId==="window/dormer","compiler-owned dormer/window authority is missing");
const dormerCut=compiled.dormers[0].cutBoundary,cutCenter:[number,number]=[dormerCut.reduce((sum,p)=>sum+p[0],0)/4,dormerCut.reduce((sum,p)=>sum+p[2],0)/4];
const containsXZ=(boundary:readonly (readonly number[])[],point:readonly [number,number])=>{let inside=false;for(let i=0,j=boundary.length-1;i<boundary.length;j=i++){const a=boundary[i],b=boundary[j];if((a[2]>point[1])!==(b[2]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[2])/(b[2]-a[2])+a[0])inside=!inside;}return inside;};
const hostFragments=compiled.primitives.filter((primitive):primitive is Extract<(typeof compiled.primitives)[number],{kind:"plane-slab"}>=>primitive.kind==="plane-slab"&&primitive.id.startsWith("roof/main-roof/south/fragment-"));
assert(hostFragments.every(fragment=>!containsXZ(fragment.boundary,cutCenter)),"an emitted host-roof fragment still covers the dormer penetration center");
const penetration=compiled.roofPenetrations[0];assert(penetration?.id==="chimney/hall"&&penetration.shaft.length===4&&penetration.curb.length===4&&penetration.flashing.length===4&&penetration.counterflashing.length===4&&penetration.cricket.length===2&&penetration.cap.length===4&&penetration.flueLiner.length===4,"chimney penetration lacks open shaft/crown, closed flashing, cricket, or liner authority");
assert(penetration.cricket[0].normal[0]*penetration.cricket[1].normal[0]<0,"chimney cricket planes do not shed toward opposite transverse sides");
assert(compiled.fireplaces[0].penetrationId===penetration.id&&compiled.fireplaces[0].chimney===undefined,"fireplace retained an independent chimney after penetration compilation");
const chimneyCenter:[number,number]=[penetration.cutBoundary.reduce((sum,p)=>sum+p[0],0)/4,penetration.cutBoundary.reduce((sum,p)=>sum+p[2],0)/4],northFragments=compiled.primitives.filter((primitive):primitive is Extract<(typeof compiled.primitives)[number],{kind:"plane-slab"}>=>primitive.kind==="plane-slab"&&primitive.id.startsWith("roof/main-roof/north/fragment-"));
assert(northFragments.length===4&&northFragments.every(fragment=>!containsXZ(fragment.boundary,chimneyCenter)),"an emitted north-roof fragment still covers the chimney cutout");
const valleys=compiled.roofSeams.filter(seam=>seam.kind==="valley");
assert(valleys.length===2,"main/service roof systems did not derive both valley intersections");
for(const valley of valleys){const length=Math.hypot(valley.to[0]-valley.from[0],valley.to[1]-valley.from[1],valley.to[2]-valley.from[2]);assert(length>2.8&&length<3.6,`${valley.id} escaped the credible valley length`);assert(valley.supported,"derived valley lacks dual-substrate authority");}
const roofSlabIds=compiled.primitives.filter(primitive=>primitive.kind==="plane-slab"&&primitive.surfaceRole==="roof").map(primitive=>primitive.id).sort();
assert(!roofSlabIds.includes("roof/main-roof/south")&&roofSlabIds.filter(id=>id.startsWith("roof/main-roof/south/fragment-")).length===4,"dormer host plane was not replaced by exactly four physical fragments");
assert(!roofSlabIds.includes("roof/main-roof/north")&&roofSlabIds.filter(id=>id.startsWith("roof/main-roof/north/fragment-")).length===4,"chimney host plane was not replaced by exactly four physical fragments");
assert(roofSlabIds.includes("roof/service-roof/east")&&roofSlabIds.includes("roof/service-roof/west"),"trimmed service-roof weather planes are missing");
assert(roofSlabIds.includes("dormer/south/roof-west")&&roofSlabIds.includes("dormer/south/roof-east"),"paired dormer roof planes are missing");
const planeSlabs=compiled.primitives.filter((primitive):primitive is Extract<(typeof compiled.primitives)[number],{kind:"plane-slab"}>=>primitive.kind==="plane-slab"),hostSouth=planeSlabs.find(primitive=>primitive.id==="roof/main-roof/south/fragment-left")!,serviceSlabs=planeSlabs.filter(primitive=>/^roof\/service-roof\/(west|east)$/.test(primitive.id));
const signed=(point:readonly number[],plane:typeof hostSouth)=>(point[0]-plane.origin[0])*plane.normal[0]+(point[1]-plane.origin[1])*plane.normal[1]+(point[2]-plane.origin[2])*plane.normal[2];
assert(serviceSlabs.length===2&&serviceSlabs.every(slab=>slab.boundary.every(point=>signed(point,hostSouth)>=-.003)&&slab.boundary.filter(point=>Math.abs(signed(point,hostSouth))<=.0031).length===2),"service roof was not physically terminated on the main-roof valley plane");
const serviceRidge=compiled.roofSeams.find(seam=>seam.id==="service-roof/ridge")!;assert(Math.abs(serviceRidge.to[2]+1.138)<.01||Math.abs(serviceRidge.from[2]+1.138)<.01,"trimmed service ridge does not terminate at the shared valley apex");
assert(["west","east"].every(side=>!compiled.primitives.some(primitive=>primitive.id===`eave-trim/service-roof/${side}/barge-1`)),"service roof retained false barge trim on its joined valley edge");
const gableIds=compiled.primitives.filter(primitive=>primitive.kind==="plane-slab"&&primitive.surfaceRole==="wall"&&primitive.id.startsWith("gable/")).map(primitive=>primitive.id);assert(gableIds.length===3&&!gableIds.includes("gable/service-roof/rear")&&gableIds.includes("gable/service-roof/front"),"joined service roof retained a false rear gable closure");
assert(["fascia-left","fascia-right","rake-left","rake-right"].every(suffix=>compiled.primitives.some(primitive=>primitive.id===`dormer/south/${suffix}`)),"dormer lacks explicit eave and rake trim");
assert([0,1,2,3].every(index=>compiled.primitives.some(primitive=>primitive.id===`dormer/south/curb-${index}`)&&compiled.primitives.some(primitive=>primitive.id===`dormer/south/counterflashing-${index}`)),"dormer curb/counterflashing ring is incomplete");
assert(compiled.primitives.every(primitive=>primitive.kind!=="box"||primitive.halfExtents.every(n=>n>0)),"volume compilation emitted a non-positive solid");
const roleById=new Map(compiled.primitives.map(primitive=>[primitive.id,primitive.materialRole]));
assert(roleById.get("dormer/south/gable-front")==="wall-exterior","dormer gable lost exterior wall material authority");
assert(roleById.get("chimney/hall/counterflashing-0")==="roof-flashing"&&roleById.get("dormer/south/flashing-apron")==="roof-flashing","lead flashing was misclassified as slate or masonry");
assert(["west","east","north","south"].every(side=>roleById.get(`chimney/hall/shaft-${side}`)==="hearth-masonry"),"open chimney shaft ring lost masonry material authority");
assert(["fireback","throat","lining-left","lining-right","smoke-shelf","smoke-chamber-west","smoke-chamber-east"].every(part=>roleById.get(`fireplace/hall-hearth/${part}`)==="hearth-masonry"),"firebox-to-flue structure or masonry authority is incomplete");
const liner=penetration.flueLiner[0],shaft=penetration.shaft[0];assert(Math.abs((liner.center[1]-liner.halfExtents[1])-(shaft.center[1]-shaft.halfExtents[1]))<=.001,"flue liner does not continue to the shaft bottom");
assert(roleById.get("window/dormer/glass")==="glazing"&&roleById.get("window/dormer/came-vertical-0")==="door-hardware","window glass/came material authority drifted");
assert(roleById.get("volume/main-hall/floor")==="floor-furnishing"&&roleById.get("volume/main-hall/ceiling")==="wall-interior","interior floor/ceiling material authority drifted");
assert(compiled.functionalContract?.buildingId==="hall-house/temperate/v4"&&compiled.functionalContract.colliders.length>=30&&compiled.functionalContract.doors.length===1,"strict functional building authority was not compiled");
assert(compiled.interiorStructure.length===18&&compiled.interiorStructure.flatMap(item=>item.parts).length===18,"authored hall load path is incomplete");
const braces=compiled.interiorStructure.filter(item=>item.kind==="knee-brace").flatMap(item=>item.parts).filter((part):part is Extract<(typeof compiled.primitives)[number],{kind:"linear-member"}>=>part.kind==="linear-member");
assert(braces.length===10&&braces.every(brace=>{const low=brace.from[1]<brace.to[1]?brace.from:brace.to,high=brace.from[1]<brace.to[1]?brace.to:brace.from;return Math.abs(low[2])>Math.abs(high[2])&&high[1]-low[1]>=.4;}),"knee braces do not rise from wall bearing toward the tie-beam load path");
const mainCeiling=compiled.volumes.find(volume=>volume.id==="main-hall")?.ceiling;
assert(mainCeiling!==undefined&&compiled.interiorStructure.filter(item=>item.kind==="tie-beam").flatMap(item=>item.parts).every(part=>part.kind!=="box"||part.center[1]+part.halfExtents[1]<=mainCeiling.bottomY+.001),"tie beams penetrate the ceiling substrate");
assert(compiled.domesticProps.length===17&&compiled.domesticProps.every(prop=>prop.parts.length>0&&Math.abs(prop.supportY-(spec.domesticProps?.find(item=>item.id===prop.id)?.supportY??NaN))<1e-6),"domestic props lost authored support authority");
assert(compiled.visualContract?.interior.furnishingNodeIds.length===compiled.furnishings.flatMap(item=>item.parts).length+compiled.interiorStructure.flatMap(item=>item.parts).length+compiled.domesticProps.flatMap(item=>item.parts).length,"visual contract omits authored interior structure or domestic detail");

const rejects=(mutate:(copy:any)=>void,pattern:RegExp)=>{const copy=structuredClone(spec);mutate(copy);let message="";try{compileArchitecture(copy);}catch(error){message=String(error);}assert(pattern.test(message),`expected ${pattern}, got ${message}`);};
rejects(copy=>copy.volumes[0].footprint.reverse(),/counter-clockwise/);
rejects(copy=>copy.volumes[0].footprint=[[-4,-3],[4,3],[-4,3],[4,-3]],/self-intersects|counter-clockwise/);
rejects(copy=>copy.volumes[1].footprint[0]=[-20,-20],/not fully supported/);
rejects(copy=>copy.volumes[0].openings[0].edgeIndex=99,/invalid volume edge/);
rejects(copy=>copy.walls=[{id:"dual",from:[0,0],to:[1,0],bottomY:0,topY:1,thickness:.1}],/volume authority or explicit wall authority/);
rejects(copy=>copy.roofSystems[0].pitchDegrees=80,/invalid roof system/);
rejects(copy=>copy.roofJunctions[0].flashingWidth=.05,/credible flashing/);
rejects(copy=>delete copy.roofJunctions[0].trimSystemId,/credible flashing/);
rejects(copy=>copy.roofJunctions[0].trimSystemId="missing",/credible flashing/);
rejects(copy=>copy.doors[0].openYawDegrees=-45,/invalid door assembly/);
rejects(copy=>copy.dormers[0].hostPlaneId="missing",/missing host roof plane/);
rejects(copy=>copy.dormers[0].downslopeRange=[.05,1],/invalid dormer/);
rejects(copy=>copy.dormers[0].width=20,/escapes host roof substrate/);
rejects(copy=>copy.dormers[0].eaveY=4.5,/invalid dormer/);
rejects(copy=>copy.dormers[0].windowSillY=5.4,/escapes dormer\/south\/front/);
rejects(copy=>copy.dormers[0].eaveOverhang=.05,/invalid dormer/);
rejects(copy=>copy.dormers[0].rakeOverhang=.05,/invalid dormer/);
rejects(copy=>copy.dormers[0].curbHeight=.05,/invalid dormer/);
rejects(copy=>copy.dormers[0].flashingWidth=.05,/invalid dormer/);
rejects(copy=>copy.roofPenetrations[0].roofPlaneId="missing",/missing fireplace or roof plane/);
rejects(copy=>copy.roofPenetrations[0].clearance=0,/invalid roof penetration/);
rejects(copy=>copy.roofPenetrations[0].center=[2.95,3.8],/flashing envelope escapes/);
rejects(copy=>copy.roofPenetrations[0].topY=4.8,/continuous shaft projection/);
console.log(`p_architecture_volume OK: ${compiled.volumes.length} closed volumes, ${compiled.walls.length} derived wall edges, ${compiled.primitives.length} resolved primitives`);
