import fs from "node:fs";
import crypto from "node:crypto";
import { compileArchitecture, type ArchitectureSpec } from "../src/architecture/index.ts";
import { parseFunctionalBuildingContract } from "../src/assets/functional-building-contract.ts";
import { parseFunctionalBuildingVisualContract } from "../src/assets/functional-building-visual-contract.ts";
import { validateMultiRoomReviewAuthority } from "../src/render/building-multi-room-review-scene.ts";

const root="assets/buildings/authoring/functional-hall-house-v4/fb4-multi-room-candidate-8ac79c90b4ac",fail=(m:string)=>{throw new Error(`p_fb4_multi_room_review_candidate FAIL: ${m}`)},ok=(v:unknown,m:string)=>{if(!v)fail(m)},raw=(b:Uint8Array)=>`sha256:${crypto.createHash("sha256").update(b).digest("hex")}`;
const manifest=JSON.parse(fs.readFileSync(`${root}/candidate-manifest.json`,"utf8")),authority=validateMultiRoomReviewAuthority(JSON.parse(fs.readFileSync(`${root}/review-authority.json`,"utf8")));
const glb=fs.readFileSync(`${root}/functional-hall-house-fb4-multi-room.glb`),contract=parseFunctionalBuildingContract(glb),visual=parseFunctionalBuildingVisualContract(glb);
ok(raw(glb)===authority.candidate.glb.sha256&&glb.length===authority.candidate.glb.bytes,"exact production GLB identity drifted");
ok(contract.schema==="limina.functional-building/v2"&&contract.rooms.length===3&&contract.verticalLinks.length===1,"strict v2 topology drifted");
ok(visual.materialRoles.some(({role})=>role==="roof")&&visual.materialRoles.some(({role})=>role==="structure-trim")&&visual.openings.length>=2,"approved visual/material authority was not retained");
const spec=JSON.parse(fs.readFileSync(`${root}/architecture-spec.json`,"utf8")) as ArchitectureSpec,compiled=compileArchitecture(spec);
ok(compiled.irHash===authority.candidate.irHash&&compiled.irHash===manifest.compiler.irHash,"compiler IR closure drifted");
const mainRoof=spec.roofSystems?.find(({id})=>id==="main-roof"),serviceRoof=spec.roofSystems?.find(({id})=>id==="service-roof");
ok(mainRoof?.volumeId==="upper-hall","main roof is not owned by the upper storey");
ok((spec.roofJunctions?.length??0)===0&&serviceRoof?.ridgeEndOverhang[1]===.12,"obsolete one-storey valley/overlap remains");
ok(spec.roofWallAbutments?.length===2&&spec.roofWallAbutments.every(a=>a.wallId==="upper-hall/edge-0"&&a.flashingWidth>=.22),"service roof lacks validated upper-wall headwall flashing");
ok(compiled.primitives.filter(p=>p.id.startsWith("roof-wall-flashing/service-upper-headwall-")).length===2,"compiler did not emit both sloped headwall flashing members");
const mainRoofSurfaces=compiled.primitives.filter((p:any)=>p.id.startsWith("roof/main-roof/")&&p.surfaceRole==="roof") as any[];
ok(mainRoofSurfaces.length>=2&&mainRoofSurfaces.every(p=>p.boundary.every((v:number[])=>Math.abs(v[2])>3.42||v[1]>=6.54)),"raised main roof intersects the upper-room volume");
const dormer=spec.dormers?.[0],penetration=spec.roofPenetrations?.[0];
ok((dormer?.wallBaseY??0)>6.5&&(dormer?.windowSillY??0)>7&&dormer?.hostPlaneId==="main-roof/south","dormer was not coherently raised with the roof");
ok((penetration?.topY??0)>10&&penetration?.roofPlaneId==="main-roof/north","chimney penetration was not raised with the roof");
ok((spec.interiorStructure?.filter(({id})=>id.startsWith("upper/")).length??0)>=12,"upper storey lacks coherent timber-frame cues");
const handoff=JSON.parse(fs.readFileSync(`${root}/authoring-handoff.json`,"utf8"));ok(handoff.schema==="limina.blender-authoring-handoff/v1"&&handoff.genericGltfExportAllowed===false,"editable Blender handoff drifted");
ok(authority.approval.humanDecision==="pending"&&authority.presentation.timestampQueriesEnabled===false&&authority.evidenceViews.length===4,"review gate is not human-pending/timestamp-disabled");
console.log(`p_fb4_multi_room_review_candidate OK: ${glb.length} bytes, coherent upper-owned roof/dormer/chimney, ${contract.rooms.length} rooms, ${contract.verticalLinks.length} stair, editable Blend, human-pending`);
