#!/usr/bin/env node
// ════════════════════════════════════════════════════════════════════════════
//  scripts/export.mjs — build dist/ from world.ts using the native `limina`.
//
//  WHAT IT DOES
//    1. Locates the native `limina` binary (LIMINA_BIN, else ./target/release/
//       limina under LIMINA_HOME) and the limina source tree (LIMINA_HOME).
//    2. Generates a tiny TypeScript export harness that imports the limina engine
//       + skills (by absolute file:// path) and YOUR world.ts, runs `buildWorld`
//       headlessly through a WorldRecorder, assembles a portable export package,
//       and round-trips it through loadExport to prove it is valid.
//    3. Runs the harness with `limina` (the native runtime has no file-write op,
//       so the harness emits the bundle JSON to stdout between markers).
//    4. Writes the bundle + the browser player + an index.html to dist/.
//
//  WHY A BINARY IS NEEDED
//    `npm run dev` plays a prebuilt sample with zero native toolchain. EXPORT,
//    though, runs your world.ts through the real deterministic engine — that is
//    the native `limina` runtime. Point at it with LIMINA_BIN, or clone+build
//    limina and we will find ./target/release/limina automatically.
// ════════════════════════════════════════════════════════════════════════════

import { spawnSync } from "node:child_process";
import {
  existsSync, mkdirSync, mkdtempSync, copyFileSync, readFileSync, writeFileSync, rmSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { tmpdir } from "node:os";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_DIR = resolve(__dirname, "..");
const WORLD_TS = join(PROJECT_DIR, "world.ts");
const DIST_DIR = join(PROJECT_DIR, "dist");
const PUBLIC_DIR = join(PROJECT_DIR, "public");

const BEGIN = "===LIMINA_BUNDLE_BEGIN===";
const END = "===LIMINA_BUNDLE_END===";

/** Print an actionable error and exit non-zero. */
function fail(msg) {
  console.error(`\n  limina export: ${msg}\n`);
  process.exit(1);
}

/** Resolve the limina binary + source home, with clear, actionable errors.
 *  - LIMINA_BIN points at the binary (any location).
 *  - LIMINA_HOME points at the limina checkout (the dir holding js/ + assets/).
 *  When only one is given we derive the other; when neither is given we probe a
 *  few conventional locations. */
function resolveLimina() {
  const env = process.env;
  let bin = env.LIMINA_BIN ? resolve(env.LIMINA_BIN) : "";
  let home = env.LIMINA_HOME ? resolve(env.LIMINA_HOME) : "";

  // Derive HOME from BIN: a binary at <home>/target/release/limina ⇒ home is two
  // dirs up. Verify by the presence of js/src/engine.ts.
  const looksLikeHome = (dir) => dir && existsSync(join(dir, "js", "src", "engine.ts"));
  if (bin && !home) {
    const guess = resolve(dirname(bin), "..", "..");
    if (looksLikeHome(guess)) home = guess;
  }
  // Derive BIN from HOME.
  if (home && !bin) {
    const guess = join(home, "target", "release", "limina");
    if (existsSync(guess)) bin = guess;
  }
  // Probe conventional locations when nothing was supplied.
  if (!bin || !home) {
    const candidates = [
      env.LIMINA_HOME && resolve(env.LIMINA_HOME),
      resolve(PROJECT_DIR, "..", "limina"),
      resolve(PROJECT_DIR, "limina"),
      process.cwd() && resolve(process.cwd(), "limina"),
    ].filter(Boolean);
    for (const dir of candidates) {
      if (!looksLikeHome(dir)) continue;
      home = home || dir;
      const guessBin = join(dir, "target", "release", "limina");
      if (!bin && existsSync(guessBin)) bin = guessBin;
      if (bin && home) break;
    }
  }

  if (!bin) {
    fail(
      "could not find the native `limina` binary.\n" +
      "  Set LIMINA_BIN to its path, e.g.:\n" +
      "      LIMINA_BIN=/path/to/limina/target/release/limina npm run export\n" +
      "  Or clone + build limina (cargo build --release) and set LIMINA_HOME to the checkout.",
    );
  }
  if (!existsSync(bin)) fail(`LIMINA_BIN does not exist: ${bin}`);
  if (!home || !looksLikeHome(home)) {
    fail(
      "found the binary but not the limina source tree (js/src/engine.ts).\n" +
      `  Set LIMINA_HOME to the limina checkout. Tried: ${home || "(none)"}`,
    );
  }
  return { bin, home };
}

/** The export harness source — runs entirely inside the native limina runtime.
 *  All limina modules are imported by ABSOLUTE file:// URL (the runtime resolves
 *  file:// specifiers and their internal relative imports), as is your world.ts,
 *  so the harness works from a temp dir outside the limina checkout. */
function harnessSource(home, worldTsAbs) {
  const u = (rel) => pathToFileURL(join(home, rel)).href;
  const world = pathToFileURL(worldTsAbs).href;
  return `// AUTO-GENERATED by scripts/export.mjs — do not edit; safe to delete.
import * as THREE from ${JSON.stringify(u("js/build/three.bundle.mjs"))};
import { EntityTable, ops } from ${JSON.stringify(u("js/src/engine.ts"))};
import { createEcsWorld } from ${JSON.stringify(u("js/src/ecs/world.ts"))};
import { createTransformStorage } from ${JSON.stringify(u("js/src/ecs/facade.ts"))};
import { UniformGridSpatialIndex } from ${JSON.stringify(u("js/src/spatial/index.ts"))};
import { LiminaTracer } from ${JSON.stringify(u("js/src/observability/event.ts"))};
import { SkillRegistry } from ${JSON.stringify(u("js/src/skills/registry.ts"))};
import { registerCoreSkills } from ${JSON.stringify(u("js/src/skills/index.ts"))};
import { resolveProfile } from ${JSON.stringify(u("js/src/skills/permissions.ts"))};
import { WorldRecorder } from ${JSON.stringify(u("js/src/worldlog/recorder.ts"))};
import { assembleExport, loadExport } from ${JSON.stringify(u("js/src/export/package.ts"))};
import { buildWorld, SEED } from ${JSON.stringify(world)};

function assert(cond, msg) { if (!cond) throw new Error("limina export FAIL: " + msg); }

// Warm THREE's lazy init on the DEFAULT rng before the seeded rng is installed,
// so the recorded run and any later replay draw the same seeded stream.
void new THREE.Mesh(new THREE.SphereGeometry(0.5, 24, 16), new THREE.MeshStandardNodeMaterial({ color: 0x808080 }));
void new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshStandardNodeMaterial({ color: 0x808080 }));

const seed = typeof SEED === "number" ? SEED : 1234;

const ecs = createEcsWorld();
const scene = new THREE.Scene();
const camera = { position: { set() {} }, aspect: 1, lookAt() {}, updateProjectionMatrix() {} };
const tracer = new LiminaTracer("ses_export_world");
const registry = new SkillRegistry(tracer);
const core = registerCoreSkills(registry);
const recorder = new WorldRecorder("ses_export_world");
recorder.attach(registry);
recorder.seed(seed); // deterministic PRNG seed -> recorded so replay reinstalls it
const recOps = recorder.wrapOps(ops);
// mode "windowed" authors the VISIBLE world (PBR surface + biome scatter) headlessly.
const world = {
  ecs, transforms: createTransformStorage(ecs), spatial: new UniformGridSpatialIndex(),
  entities: new EntityTable(), tags: new Map(), scene, camera, ops: recOps, mode: "windowed",
};
const base = { agentId: "agt_export_world", sessionId: "ses_export_world", permissions: resolveProfile("builder.readWrite"), tick: 0, world };

// Recorded so a replay recreates the physics world before re-applying state.
recOps.op_physics_create_world(-9.81);

if (typeof buildWorld !== "function") {
  throw new Error("world.ts must \`export const buildWorld\` (an async function)");
}
const built = (await buildWorld({ world, registry, core, base })) ?? {};

const tileEntries = core.terrain.cache.entries();
const assetBundle = core.assets.bundle();
const files = assembleExport({
  worldId: "limina-world",
  meta: recorder.meta(),
  commands: recorder.commands,
  keyframes: [],
  keyframeInterval: 20,
  createdAt: "2026-01-01T00:00:00Z",
  tiles: tileEntries,
  assets: assetBundle,
});

// VERIFY: loadExport round-trips (the exact files a browser reads back).
const loaded = loadExport(files, ops);
assert(loaded.manifest.kind === "limina.export", "manifest kind wrong");
assert(loaded.manifest.exportVersion === 1, "manifest exportVersion wrong");
assert(loaded.commands.length === recorder.commands.length, "command count lost on round-trip");
assert(loaded.tiles.length === tileEntries.length, "tile count lost on round-trip");
assert(loaded.assets.length === assetBundle.length, "asset count lost on round-trip");

// Camera framing (buildWorld may return one; else a sane default orbit).
const view = built.view ?? { center: [0, 1, 0], radius: 24, height: 12, maxRadius: 60, maxHeight: 40, far: 600 };

console.log(
  "EXPORT OK: " + loaded.commands.length + " commands, " + loaded.tiles.length + " tiles, " +
  loaded.assets.length + " assets" + (built.summary ? " — " + built.summary : ""),
);
console.log(${JSON.stringify(BEGIN)});
console.log(JSON.stringify({ files, view }));
console.log(${JSON.stringify(END)});
`;
}

/** The dist/index.html — the same player page as public/index.html, but framing
 *  the world that sits at the dist root (data-world="./"). */
function distIndexHtml() {
  const src = join(PUBLIC_DIR, "index.html");
  if (!existsSync(src)) fail(`missing ${src} (scaffold is incomplete)`);
  const html = readFileSync(src, "utf8");
  // public/index.html points the dev sample at island/; dist serves the world at root.
  return html.replace(/data-world="[^"]*"/, 'data-world="./"');
}

function main() {
  if (!existsSync(WORLD_TS)) fail(`no world.ts found at ${WORLD_TS}`);
  const { bin, home } = resolveLimina();
  console.log(`limina export: using binary ${bin}`);
  console.log(`limina export: using source  ${home}`);

  // Generate the harness in a temp dir (cleaned up afterwards).
  const work = mkdtempSync(join(tmpdir(), "limina-export-"));
  const entry = join(work, "export-entry.ts");
  writeFileSync(entry, harnessSource(home, WORLD_TS));

  // Run the harness. cwd MUST be the limina checkout so op_read_asset resolves
  // scatter GLBs from <home>/assets. The entry path is absolute, so cwd does not
  // affect module resolution.
  let res;
  try {
    res = spawnSync(bin, [entry], {
      cwd: home,
      encoding: "utf8",
      maxBuffer: 256 * 1024 * 1024,
    });
  } finally {
    rmSync(work, { recursive: true, force: true });
  }

  if (res.error) fail(`failed to launch limina: ${res.error.message}`);
  if (res.status !== 0) {
    process.stderr.write(res.stderr || "");
    fail(`limina exited with code ${res.status}. The harness/world.ts threw (see above).`);
  }

  const out = res.stdout || "";
  // Surface the harness's progress line (everything before the bundle markers).
  const pre = out.slice(0, out.indexOf(BEGIN) === -1 ? out.length : out.indexOf(BEGIN)).trim();
  if (pre) console.log(pre);

  const b = out.indexOf(BEGIN);
  const e = out.indexOf(END);
  if (b === -1 || e === -1 || e < b) {
    process.stderr.write(res.stderr || "");
    fail("export bundle markers not found in limina output (the harness did not finish).");
  }
  let parsed;
  try {
    parsed = JSON.parse(out.slice(b + BEGIN.length, e).trim());
  } catch (err) {
    fail(`failed to parse the export bundle JSON: ${err.message}`);
  }
  const { files, view } = parsed;

  // Write dist/: the bundle + view, the browser player, and the page.
  mkdirSync(DIST_DIR, { recursive: true });
  const written = [];
  for (const [name, content] of Object.entries(files)) {
    const required = name === "manifest.json" || name === "log.jsonl" || name === "keyframes.jsonl";
    if (!required && (content === undefined || content.length === 0)) continue;
    writeFileSync(join(DIST_DIR, name), content);
    written.push(`${name} (${content.length}B)`);
  }
  writeFileSync(join(DIST_DIR, "view.json"), JSON.stringify(view, null, 2) + "\n");
  written.push("view.json");

  const playerSrc = join(PUBLIC_DIR, "limina-player.js");
  if (!existsSync(playerSrc)) fail(`missing ${playerSrc} (scaffold is incomplete)`);
  copyFileSync(playerSrc, join(DIST_DIR, "limina-player.js"));
  written.push("limina-player.js");

  writeFileSync(join(DIST_DIR, "index.html"), distIndexHtml());
  written.push("index.html");

  console.log(`\nWrote dist/ (${written.length} files):\n  ${written.join("\n  ")}`);
  console.log(`\nPlay it:  npm run serve`);
}

main();
