import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs";
import test from "node:test";
import { FB4_CAPTURE } from "./run-native-fb4-multi-room-capture.mjs";

const runner=fs.readFileSync(new URL("./run-native-fb4-multi-room-capture.mjs",import.meta.url),"utf8"),producer=fs.readFileSync(new URL("./capture-producer-closure.mjs",import.meta.url),"utf8"),demo=fs.readFileSync(new URL("../../js/src/demos/building_multi_room_review_window.ts",import.meta.url),"utf8"),scene=fs.readFileSync(new URL("../../js/src/render/building-multi-room-review-scene.ts",import.meta.url),"utf8");
const authorityPath="../../assets/buildings/authoring/functional-hall-house-v4/fb4-multi-room-candidate-d0ca1e327841/review-authority.json",authority=JSON.parse(fs.readFileSync(new URL(authorityPath,import.meta.url),"utf8")),raw=b=>`sha256:${createHash("sha256").update(b).digest("hex")}`;
test("FB-4 authority pins the program-derived append-only candidate and exact eight-view HITL gate",()=>{assert.deepEqual(authority.evidenceViews.map(({id})=>id),FB4_CAPTURE.viewIds);assert.equal(authority.schema,"limina.fb4-multi-room-review-authority/v2");assert.equal(authority.approval.humanDecision,"pending");assert.equal(authority.approval.visualApprovalClaimed,false);assert.equal(authority.presentation.timestampQueriesEnabled,false);assert.equal(authority.topologyProof.expectedDoors,3);assert.equal(authority.topologyProof.expectedAnchors,5);for(const entry of [authority.candidate.manifest,authority.candidate.glb,authority.visualFloor.releaseContract,authority.environment.authority,authority.environment.runtimeBundle])assert.equal(raw(fs.readFileSync(new URL(`../../${entry.path}`,import.meta.url))),entry.sha256);});
test("rejected V2 authority is historical and cannot launch another GPU capture",()=>{assert.match(runner,/assertMultiRoomReviewCaptureReady\(validateMultiRoomReviewAuthority/);assert.match(scene,/V2 review authority is historical only/);assert.match(demo,/assertMultiRoomReviewCaptureReady/);assert.match(demo,/verifySiteReviewRuntimePack/);assert.match(demo,/verifySiteReviewCameras/);assert.match(demo,/discretePopulationHardExclusionAt/);});
test("FB-4 scene places only through functional engine skills and proves authority-owned layered topology",()=>{assert.match(scene,/registry\.invoke\("building\.placeFunctional"/);assert.match(scene,/registry\.invoke\("building\.findRoomPath"/);assert.match(scene,/authority\.topologyProof\.fromRoomId/);assert.match(scene,/authority\.topologyProof\.connectionIds/);assert.match(scene,/building\.destroyFunctional/);assert.doesNotMatch(scene,/loadGltfIntoScene|parseGltfScene/);});
test("FB-4 demo is production native, timestamp-disabled, whole-frame, and uses approved temperate context",()=>{assert.match(demo,/createEngine\(\{width,height,gpuTimestampMode:"disabled",gpuTextureCompression:"bc-required",renderBaseline:false\}\)/);assert.match(demo,/mountTemperateFidelityScene/);assert.match(demo,/populationHardExclusionAt:site\.containsWorldXZ/);assert.match(demo,/mountMultiRoomReview/);assert.match(demo,/requireWholeFrameRenderSubmissionTelemetry/);assert.match(demo,/readNativeSurfaceRgba/);assert.match(demo,/limina\.fb4-multi-room-native-review-set\/v1/);assert.doesNotMatch(demo,/timestamp-query|requiredFeatures/);});
test("FB-4 launcher is private, append-only, Xid guarded, timestamp-scrubbed, and does not auto-stage below-floor captures",()=>{assert.equal(FB4_CAPTURE.binary,"target/release/limina");assert.equal(FB4_CAPTURE.reviewBindHost,"127.0.0.1");assert.equal(FB4_CAPTURE.reviewRoot,".limina/review-artifacts");assert.match(runner,/current boot already contains an NVIDIA Xid/);assert.match(runner,/journalctl",\["-k","-f","-n","0"/);assert.match(runner,/setInterval\(.*kernelLog\(\).*250/s);assert.match(runner,/must not be retried before reboot/);assert.match(runner,/do not retry until reboot/);assert.match(runner,/for\(const key of Object\.keys\(environment\)\)if\(\/TIMESTAMP\/i\.test\(key\)\)delete environment\[key\]/);assert.match(runner,/options\.fullscreen\?\["--fullscreen"\]:\[\]/);assert.match(runner,/args\.includes\("--fullscreen"\)/);assert.match(runner,/mkdir\(dirname\(out\),\{recursive:true,mode:0o700\}\)/);assert.match(runner,/append-only/);assert.match(runner,/reviewBridge:\{artifactDirectory:FB4_CAPTURE\.reviewRoot,bindHost:FB4_CAPTURE\.reviewBindHost,public:false,staged:false/);assert.doesNotMatch(runner,/reviewArtifactPath|writeFile\(reviewPath|requiredFeatures.*timestamp-query/);});
test("FB-4 launcher binds complete producer provenance without retaining traces or serializing credentials",()=>{assert.deepEqual(FB4_CAPTURE.sourcePaths,["js/src/render/building-multi-room-review-scene.ts","js/src/demos/building_multi_room_review_window.ts","tools/preview/run-native-fb4-multi-room-capture.mjs"]);assert.match(runner,/buildCaptureProducerClosure/);assert.match(runner,/\/proc\/sys\/kernel\/random\/boot_id/);assert.match(runner,/traceBytes=await readFile\(tracePath\)/);assert.match(runner,/await unlink\(tracePath\)/);assert.match(runner,/capture-provenance\.json/);assert.match(producer,/timestampEnvironmentKeys/);assert.match(producer,/collectCaptureModuleClosure/);assert.match(runner,/flag:"wx",mode:0o600/);assert.doesNotMatch(runner,/JSON\.stringify\(environment|environment:\{\.\.\.process\.env\}/);});
