<#
  limina MCP installer (Windows / PowerShell).

  Mirrors install.sh: builds/locates limina.exe, generates a .cmd wrapper that
  cd's to the repo (the runtime loads js/src/mcp/stdio_runtime.ts relative to
  CWD), and registers limina as a spec-compliant stdio MCP server in the
  harnesses you select. Backs up every edited config; re-running is idempotent.

  NOTE: the JSON/TOML/CLI logic matches the Linux/macOS installer that was
  verified end-to-end, but this PowerShell port has NOT been run on Windows yet.
  Treat first run as a smoke test; configs are backed up (.bak) regardless.

    .\install.ps1            interactive (from a cloned repo)
    irm https://www.liminaengine.com/install.ps1 | iex   (remote: clone + build)
    .\install.ps1 -DryRun    show the plan, write nothing
    .\install.ps1 -Yes       skip the confirm prompt

  Env: LIMINA_DIR (clone target, default %USERPROFILE%\.limina)
       LIMINA_HARNESSES (non-interactive selection: all | detected | comma,list)
#>
[CmdletBinding()]
param([switch]$DryRun, [switch]$Yes)
$ErrorActionPreference = "Stop"

function Say($m){ Write-Host $m }
function Bold($m){ Write-Host $m -ForegroundColor Cyan }
function Warn($m){ Write-Host $m -ForegroundColor Yellow }

$Name      = "limina"
$APPDATA   = $env:APPDATA
$USER      = $env:USERPROFILE
$Repo      = if ($MyInvocation.MyCommand.Path) { Split-Path -Parent $MyInvocation.MyCommand.Path } else { "" }
$RepoUrl   = if ($env:LIMINA_REPO_URL) { $env:LIMINA_REPO_URL } else { "https://github.com/syndicalt/limina.git" }
$LiminaDir = if ($env:LIMINA_DIR) { $env:LIMINA_DIR } else { Join-Path $USER ".limina" }
$Bootstrap = $false

# Bootstrap when run outside a checkout (irm | iex): clone the repo + build.
if (-not $Repo -or -not (Test-Path (Join-Path $Repo "js\src\mcp\stdio_runtime.ts"))) {
  $Bootstrap = $true
  $Repo = $LiminaDir
  if ($DryRun) {
    Warn "(dry-run) would clone $RepoUrl -> $LiminaDir and build"
  } else {
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) { throw "git is required to bootstrap limina." }
    if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) { throw "Rust/cargo is required to build limina - see https://rustup.rs" }
    if (Test-Path (Join-Path $Repo "js\src\mcp\stdio_runtime.ts")) {
      Bold "Updating limina checkout in $Repo"; Push-Location $Repo; git pull --ff-only; Pop-Location
    } else {
      Bold "Cloning limina into $Repo"; git clone --depth 1 $RepoUrl $Repo
    }
  }
}
$Bin     = Join-Path $Repo "target\release\limina.exe"
$Wrapper = Join-Path $Repo "bin\limina-mcp.cmd"

# 1. binary
if (-not (Test-Path $Bin)) {
  if ($DryRun) { Warn "(dry-run) would build limina.exe with 'cargo build --release'" }
  elseif ($Bootstrap) {
    if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) { throw "Rust/cargo is required - see https://rustup.rs" }
    Bold "Building limina from source (compiles a Rust project - a few minutes)..."
    Push-Location $Repo; cargo build --release; Pop-Location
  } else {
    Warn "limina.exe not found at $Bin"
    if ((Read-Host "Build now with 'cargo build --release'? [y/N]") -match '^[Yy]') {
      Push-Location $Repo; cargo build --release; Pop-Location
    } else { throw "Cannot continue without the binary." }
  }
} else { Say "OK limina binary: $Bin" }

# 2. wrapper (.cmd)
if (-not $DryRun) {
  New-Item -ItemType Directory -Force -Path (Split-Path $Wrapper) | Out-Null
  @"
@echo off
rem Auto-generated by install.ps1 — launch limina's MCP server from the repo root.
cd /d "$Repo"
"$Bin" --mcp-stdio %*
"@ | Set-Content -Encoding ASCII $Wrapper
  Say "OK wrapper: $Wrapper"
} else { Say "OK (dry-run) would write wrapper: $Wrapper" }

# JSON merge: $Parent.$Name = {command,args,[extra]}
function Merge-Json($File, $Parent, $Extra) {
  if ($DryRun) { Say "  would merge into $File ($Parent.$Name)"; return }
  New-Item -ItemType Directory -Force -Path (Split-Path $File) | Out-Null
  $data = [ordered]@{}
  if (Test-Path $File) {
    Copy-Item $File "$File.bak" -Force
    try { $data = Get-Content $File -Raw | ConvertFrom-Json -AsHashtable }
    catch { Say "  ! $File is not valid JSON; wrote nothing, left .bak"; return }
  }
  if (-not $data.ContainsKey($Parent)) { $data[$Parent] = @{} }
  $entry = @{ command = $Wrapper; args = @() }
  if ($Extra) { foreach ($k in $Extra.Keys) { $entry[$k] = $Extra[$k] } }
  $data[$Parent][$Name] = $entry
  ($data | ConvertTo-Json -Depth 12) | Set-Content -Encoding UTF8 $File
  Say "  OK $File"
}

# Codex TOML fallback
function Write-Toml($File) {
  if ($DryRun) { Say "  would add [mcp_servers.$Name] to $File"; return }
  New-Item -ItemType Directory -Force -Path (Split-Path $File) | Out-Null
  $text = ""
  if (Test-Path $File) { Copy-Item $File "$File.bak" -Force
    $text = (Get-Content $File -Raw) -replace "(?ms)\r?\n\[mcp_servers\.$Name\].*?(?=\r?\n\[|\z)", "" }
  $block = "`n[mcp_servers.$Name]`ncommand = `"$Wrapper`"`nargs = []`n"
  Set-Content -Encoding UTF8 $File ($text.TrimEnd() + "`n" + $block)
  Say "  OK $File"
}

function Write-YamlSnippet($File, $Kind) {
  Warn "  PowerShell has no YAML writer — add this to $File manually:"
  if ($Kind -eq "continue") { Say "  mcpServers:`n    - name: $Name`n      command: $Wrapper`n      args: []" }
  else { Say "  extensions:`n    ${Name}:`n      type: stdio`n      name: $Name`n      cmd: $Wrapper`n      enabled: true" }
}

# 3. harness table
$H = @(
  @{ key="claude-code";    label="Claude Code (CLI)"; detect={ Get-Command claude -ErrorAction SilentlyContinue } }
  @{ key="claude-desktop"; label="Claude Desktop";    path="$APPDATA\Claude\claude_desktop_config.json" }
  @{ key="codex";          label="OpenAI Codex CLI";  detect={ Get-Command codex -ErrorAction SilentlyContinue }; path="$USER\.codex\config.toml" }
  @{ key="cursor";         label="Cursor";            path="$USER\.cursor\mcp.json" }
  @{ key="windsurf";       label="Windsurf";          path="$USER\.codeium\windsurf\mcp_config.json" }
  @{ key="cline";          label="Cline (VS Code)";   path="$APPDATA\Code\User\globalStorage\saoudrizwan.claude-dev\settings\cline_mcp_settings.json" }
  @{ key="lmstudio";       label="LM Studio";         path="$USER\.lmstudio\mcp.json" }
  @{ key="continue";       label="Continue.dev";      path="$USER\.continue\config.yaml" }
  @{ key="goose";          label="Goose";             path="$APPDATA\Block\goose\config\config.yaml" }
  @{ key="zed";            label="Zed";               path="$APPDATA\Zed\settings.json" }
)
function Is-Detected($h){ if ($h.detect){ [bool](& $h.detect) } elseif ($h.path){ Test-Path $h.path } else { $false } }

function Write-Harness($h) {
  switch ($h.key) {
    "claude-code" {
      if (Get-Command claude -ErrorAction SilentlyContinue) {
        if (-not $DryRun) { claude mcp add --scope user --transport stdio $Name -- $Wrapper | Out-Null }
        Say "  OK claude mcp add ($Name)"
      } else { Merge-Json "$USER\.claude.json" "mcpServers" $null }
    }
    "codex" {
      if (Get-Command codex -ErrorAction SilentlyContinue) {
        if (-not $DryRun) { codex mcp add $Name -- $Wrapper | Out-Null }
        Say "  OK codex mcp add ($Name)"
      } else { Write-Toml $h.path }
    }
    "cline" { Merge-Json $h.path "mcpServers" @{ disabled=$false; autoApprove=@() } }
    "zed"   { Merge-Json $h.path "context_servers" @{ enabled=$true } }
    "continue" { if ($DryRun) { Say "  would add to $($h.path)" } else { Write-YamlSnippet $h.path "continue" } }
    "goose"    { if ($DryRun) { Say "  would add to $($h.path)" } else { Write-YamlSnippet $h.path "goose" } }
    default { Merge-Json $h.path "mcpServers" $null }
  }
}

# 4. menu
Bold "limina MCP installer (Windows)"
Say ""
Bold "Select harnesses to register limina into:"
for ($i=0; $i -lt $H.Count; $i++) {
  $mark = if (Is-Detected $H[$i]) { "[detected]" } else { "[not found]" }
  "{0,2}) {1,-22} {2}" -f ($i+1), $H[$i].label, $mark | Write-Host
}
$choice = if ($env:LIMINA_HARNESSES) { $env:LIMINA_HARNESSES } else { Read-Host "`nEnter numbers (e.g. 1,3,5), 'all', 'detected', or 'q'" }
if ($choice -eq 'q') { return }
$sel = switch ($choice) {
  'all'      { $H }
  'detected' { $H | Where-Object { Is-Detected $_ } }
  default    { $choice -split ',' | ForEach-Object { $n=[int]($_.Trim()); if ($n -ge 1 -and $n -le $H.Count) { $H[$n-1] } } }
}
if (-not $sel) { Say "nothing selected."; return }

Bold "`nPlan:"; $sel | ForEach-Object { Say "  - $($_.label)" }
Say "  wrapper command: $Wrapper"
if ($DryRun) { Warn "(dry-run — nothing will be written)" }
elseif (-not $Yes) { if ((Read-Host "`nApply? [y/N]") -notmatch '^[Yy]') { return } }

Say ""
foreach ($h in $sel) { Bold "-> $($h.label)"; Write-Harness $h }

Bold "`nDone."
@"
Next steps:
  * Fully quit & relaunch GUI apps (Claude Desktop, Cursor, Windsurf, LM Studio, Zed) to reload config.
  * Server name "$Name"; it grants the 'builder.readWrite' profile.
  * Backups of edited configs saved as <file>.bak.
  * Continue/Goose use YAML — paste the printed snippet (no PowerShell YAML writer).
"@ | Write-Host
