// limina UI — embedded monospace bitmap font (8-bit alpha-coverage atlas).
//
// Baked OFFLINE (one-time) from DejaVu Sans Mono (size 15) with PIL and embedded
// here as a base64 string of RAW 8-bit alpha bytes — one byte of coverage (0..255)
// per glyph pixel, row-major top->bottom, glyphs in ASCII order. This keeps the
// font fully OFFLINE and DECODE-FREE at runtime: no image decoder (no PNG/JPEG),
// no font parser (no TTF/woff), no DOM, no 2D canvas, no runtime dependency.
// base64 -> bytes is pure arithmetic (decodeBase64 below), not an asset decode.
//
// Covers printable ASCII 0x20..0x7E (space..tilde). Anti-aliased grayscale
// coverage gives crisp, legible glyphs; the cell is a fixed monospace box so
// layout is a multiply. To re-bake (e.g. a different face/size), regenerate the
// atlas with the same packing and replace ATLAS_B64 + the metric constants.

/** First ASCII code point in the atlas (space). */
export const FONT_FIRST_CODE = 0x20;
/** Last ASCII code point in the atlas (tilde). */
export const FONT_LAST_CODE = 0x7e;
/** Glyph cell width in source pixels (monospace). */
export const GLYPH_W = 9;
/** Glyph cell height in source pixels. */
export const GLYPH_H = 18;
/** Baseline row offset from the cell top, in source pixels (== font ascent). */
export const GLYPH_BASELINE = 14;
/** Horizontal advance in source pixels (monospace == cell width). */
export const GLYPH_ADVANCE = 9;

const GLYPH_BYTES = GLYPH_W * GLYPH_H;
const FALLBACK_CODE = 0x3f; // '?' for any code outside the atlas range

const ATLAS_B64 = [
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOP9EAAAAAAAAOP9EAAAAAAAAOP9EAAAAAAAAOP9EAAAA",
  "AAAANv9CAAAAAAAAKf80AAAAAAAAGP8kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOP9EAAAAAAAAOP9EAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIwAC4kAAAAACIwAC4kAAAAACIwAC4",
  "kAAAAACIwAC4kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASeIAUdoAAAAA",
  "iqEAkpkAAAAAy2AA01gAJP//////////AABL4ABX1QAAAACAqwCLoQAAAAC1dgC+bQAA/P////////8oADnwAkHqAQAAAHqxAIKp",
  "AAAAALtwAMNoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgQAAAA",
  "AAAAAKgQAAAAAABc0fzghQ4AAET5SKssdWUAAI3DAKgQAAAAAHnnEKgQAAAAABLX6+dtGgAAAAAHWdbe9lsAAAAAAKgQiPYGAAAA",
  "AKgQQ/8XAINyJqolsMUAABeI1f3nnxYAAAAAAKgQAAAAAAAAAKgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAADKryuxoAAAAAhqQOf6kAAAAAuUYAG98AAAAAiJ8Nf60AACAhDq3zvyJVuLw5AAAojNCFIgAAJ76vTBy88qkM",
  "DBgAAKaBDqOHAAAAANkiAEO/AAAAAKl/DaCNAAAAABy/868PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABn3fz/aAAAACT/VgQAAAAAAC3/IwAAAAAAAADFrwEAAAAAAE3u82wAAAAAGfJPYvYo",
  "AGPIcdQAALHNBXC1jsAAABfrhaGBaPESAABS/PMjDd7AKwtX9uMMAB2r8u++UuSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/qOQAAAAAAAIy2AAAAAAAADvNPAAAA",
  "AAAAY/UFAAAAAAAApMAAAAAAAAAAy54AAAAAAAAA25AAAAAAAAAAy54AAAAAAAAApMAAAAAAAAAAY/UFAAAAAAAADvNPAAAAAAAA",
  "AIy2AAAAAAAAAA/qOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAy7RMAAAAAAAAArpMA",
  "AAAAAAAASPYQAAAAAAAAA/BnAAAAAAAAALmqAAAAAAAAAJfSAAAAAAAAAIniAAAAAAAAAJfSAAAAAAAAALmqAAAAAAAAA/BnAAAA",
  "AAAASvYRAAAAAAAAsJMAAAAAAAAy7RMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "ANgAAAAAAH+CC9gKfoQAAAFSuPG4VgEAAAFRuPG4VQEAAH+DC9gKf4UAAAAAANgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHP8gAAAAAAAAHP8gAAAAAAAAHP8gAAAAXP////////9kAAAA",
  "HP8gAAAAAAAAHP8gAAAAAAAAHP8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVP+EAAAAAAAAYP9qAAAAAAAAouAHAAAAAAAB51oAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAABk////bAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbP9sAAAAAAAAbP9sAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuqkAAAAAAAA1/i8A",
  "AAAAAACwswAAAAAAACz+OQAAAAAAAKa9AAAAAAAAJPxCAAAAAAAAnMcAAAAAAAAc+UwAAAAAAACS0QAAAAAAABb2VgAAAAAAAIjZ",
  "AgAAAAAAEPJhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABM1PjV",
  "UAAAADH6cglt+zMAAKDWAAAA0qUAAN6bAAAAleQAAPyARfFKev8EBf95SfJMcv8NAPyAAAAAev8EAN6bAAAAleQAAKDWAAAA0qUA",
  "ADH6cQhs+zQAAABN1fnXUQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAJIsPzAAAAAADG4UbzAAAAAAAAAALjAAAAAAAAAALjAAAAAAAAAALjAAAAAAAAAALjAAAAAAAAAALjAAAAAAAAAALjA",
  "AAAAAAAAALjAAAAAAAAAALjAAAAAAAT///////8EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAACmj4/DBPwAAAMy1KA+G+TIAAHMCAAAB6pAAAAAAAAAA5aMAAAAAAABB/1sAAAAAAA/dwgIAAAAA",
  "BbveFwAAAAABouolAAAAAACI8TEAAAAAAG/2PQAAAAAAAOT//////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABuN3vHCQAAAAI5nHg99+TAAAAAAAAAA5ogAAAAAAAAA5ZIAAAAAABGF9TEA",
  "AAAc///2UgAAAAAAABBn+FQAAAAAAAAAqs4AAAAAAAAAq9oAAL5HEhFl/H8AAD+z6PLPZwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADT83AAAAAAABtPd3AAAAAAAgq2c3AAAAAAw7x2c",
  "3AAAAATPdQCc3AAAAH3UBQCc3AAAIvg+AACc3AAAQP////////9QAAAAAACc3AAAAAAAAACc3AAAAAAAAACc3AAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHz//////wwAAHzcAAAAAAAAAHzc",
  "AAAAAAAAAHzcAAAAAAAAAHz57/DCPwAAAGdbEB6b/DYAAAAAAAAC26YAAAAAAAAAsssAAAAAAAAC2rAAALJCDxuU/D8AAEPA7uu6",
  "OQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjre/whwYA",
  "ABbopBwMcT0AAIrbBAAAAAAAANWIAAAAAAAAAPl7tfbghwcABf/1Zw097YgAAPzCAAAAjeoAAOCgAAAAb/8GAKfBAAAAjegAADn8",
  "ZQw87YQAAABR0/jeggYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAPz//////+EAAAAAAAAF65QAAAAAAABS/zMAAAAAAACz0gAAAAAAABj7cQAAAAAAAHb6FgAAAAAAANavAAAAAAAAOP9OAAAA",
  "AAAAmekEAAAAAAAJ8IwAAAAAAABb/ywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAABt2PbacQAAAGP9UwtL+2gAALTDAAAAu7sAAK/BAAAAubYAAD71TgpJ9EQAAABt+//8cwAAAH3sPwo9",
  "6YUAAPKJAAAAgvgDAvaKAAAAgvkFAKXtQAk66KsAAAyL3/jgjg0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaB3PfSTwAAAIfsPQ1s/DQAAOqJAAAAyKEABv9rAAAApNsAAOuHAAAAx/gAAIzq",
  "Ogxq9f8BAAiL4fazf/UAAAAAAAAAjNAAAAAAAAAE3YUAADxuEhuk5hQAAAaJ6fCtIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbP9sAAAA",
  "AAAAbP9sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbP9sAAAAAAAAbP9sAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAbP9sAAAAAAAAbP9sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVP+EAAAAAAAAYP9qAAAA",
  "AAAAouAHAAAAAAAB51oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAADSalcAAAAKIjl7JYhDWbH9qlOBQAAXP+/HAAAAAAADWfI9qpOBgAAAAAAKInl7ZgiAAAAAAAD",
  "SqpcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXP////////9kAAAAAAAAAAAAAAAAAAAAAAAAXP////////9kAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVaxMBAAAAAAAHpPq54srAAAAAAAES6b1ymkPAAAAAAAZuv9k",
  "AAAFTKf1y2oPH5Xr54wrAAAAVa1NBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANjzPTgegAAADScLwpe/l4AAAAAAAAA65EAAAAAAABS/04AAAAAAEf4ggAAAAAAFfKK",
  "AAAAAAAATv8RAAAAAAAAYP8EAAAAAAAAAAAAAAAAAAAAcP8MAAAAAAAAcP8MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyr+zywDMAAErtbRcOZe0aEOxIAAAAAKB3bLoA",
  "D6Tv0qWbqnEAmrgWKt+gxFMA6DwAAHigw1QA6DsAAHigpHgAmrgWKd+gX8wAD6Tw1KGgB91sAAAAAAAAAC/nkioFAAAAAAAXjNj3",
  "8GMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiP+OAAAAAAAA1uDdAAAAAAAj/1v/KwAA",
  "AABy6QHieQAAAADApACdxwAAABL7XQBW/hcAAF3+GAAS/WQAAKv//////7IABvJ1AAAAcvYJR/8xAAAALP9OlewBAAAAAOacAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMj///rcggcAAMi0AAU5",
  "7IsAAMi0AAAAmt0AAMi0AAAAoeMAAMi0AAU+8YYAAMj/////sgkAAMi0AAQqw8IBAMi0AAAAQP84AMi0AAAAOf9AAMi0AAMjtuQM",
  "AMj///zkpycAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO",
  "juP1xD0AAAXIyy0La9gAAGr7HgAAAFUAAMDDAAAAAAAAAOycAAAAAAAAAPiSAAAAAAAAAOycAAAAAAAAAMLDAAAAAAAAAG76HQAA",
  "AFQAAAfNySwKaNgAAAAQkuT1xT0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAP//+t+WGgAAAP98Bi605BYAAP98AAAI55MAAP98AAAAoeEAAP98AAAAgP8IAP98AAAAdv8UAP98AAAAf/8JAP98",
  "AAAAoOIAAP98AAAH5pUAAP98BS2y5hgAAP//+uCYGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAJD///////AAAJDsAAAAAAAAAJDsAAAAAAAAAJDsAAAAAAAAAJDsAAAAAAAAAJD//////7gA",
  "AJDsAAAAAAAAAJDsAAAAAAAAAJDsAAAAAAAAAJDsAAAAAAAAAJD///////8UAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEz///////8kAEz/MAAAAAAAAEz/MAAAAAAAAEz/MAAAAAAAAEz/MAAA",
  "AAAAAEz//////7AAAEz/MAAAAAAAAEz/MAAAAAAAAEz/MAAAAAAAAEz/MAAAAAAAAEz/MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnrO7vsigAACTtnBoQircAAK7UAgAAAFYACfuA",
  "AAAAAAAAMP9ZAAAAAAAAPP9OAADs//8YMP9YAAAAVP8YCvt8AAAAVP8YALLLAAAAVP8YACjwkRYNjf8YAAArsfDyymICAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP98AAAAdP8IAP98AAAAdP8I",
  "AP98AAAAdP8IAP98AAAAdP8IAP98AAAAdP8IAP////////8IAP98AAAAdP8IAP98AAAAdP8IAP98AAAAdP8IAP98AAAAdP8IAP98",
  "AAAAdP8IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIj/////",
  "/4wAAAAAPP9AAAAAAAAAPP9AAAAAAAAAPP9AAAAAAAAAPP9AAAAAAAAAPP9AAAAAAAAAPP9AAAAAAAAAPP9AAAAAAAAAPP9AAAAA",
  "AAAAPP9AAAAAAIj//////4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAABE/////wAAAAAAAAB8/wAAAAAAAAB8/wAAAAAAAAB8/wAAAAAAAAB8/wAAAAAAAAB8/wAAAAAAAAB8/wAAAAAAAACE",
  "9QAALTYAAACk1AAANO5WCz7ygQAAA2nN9uqUBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAP98AAAAXv1gAP98AABS/G0AAP98AEf5ewAAAP98PfaJAAAAAP+u8csAAAAAAP//yf9EAAAAAP+y",
  "ArjhDgAAAP98AB/znAAAAP98AABu/0kAAP98AAACxuQQAP98AAAAKfmhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGz/EAAAAAAAAGz/EAAAAAAAAGz/EAAAAAAAAGz/EAAAAAAAAGz/EAAAAAAA",
  "AGz/EAAAAAAAAGz/EAAAAAAAAGz/EAAAAAAAAGz/EAAAAAAAAGz/EAAAAAAAAGz///////9YAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYP/HAAAAxf9kYP/nIAAd6f1kYP+UdgB1l/xkYP89zgDN",
  "QPxkYP8B5EvmAvxkYP8Aj+eSAPxkYP8AOP87APxkYP8AAAAAAPxkYP8AAAAAAPxkYP8AAAAAAPxkYP8AAAAAAPxkAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPz8GwAAbP8EAPz/gAAAbP8EAPzG",
  "5AMAbP8EAPx45VAAbP8EAPx0gbgAbP8EAPx0HPoibP8EAPx0ALGIbP8EAPx0AEnqcv8EAPx0AALexf8EAPx0AAB5//8EAPx0AAAW",
  "+f8EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABc2PnaYgAA",
  "AEf9XAhX/U4AALy9AAAAuMMAAveGAAAAgPsFGP9vAAAAaP8fIf9pAAAAYv8pGP9vAAAAaP8fAviGAAAAgPwFAL+8AAAAt8QAAE39",
  "WgdW/VAAAABh2vrcZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAJD///3hnRgAAJDsAAM13soDAJDsAAAAXf8zAJDsAAAAOf9RAJDsAAAAXf80AJDsAAI13c4DAJD///3ioRsAAJDsAAAAAAAA",
  "AJDsAAAAAAAAAJDsAAAAAAAAAJDsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAABc2PnaYgAAAEf9XAhX/U4AALy9AAAAuMMAAveGAAAAgPsFGP9vAAAAaP8fIf9pAAAAYv8oGP9vAAAA",
  "aP8bAveGAAAAgPoHAL28AAAAt8UAAEn9WgdW/VQAAABf2v3/ggAAAAAAAAbA2RkAAAAAAAARwj0AAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPT///LOYQAAAPSIAA9z/14AAPSIAAAA1rUAAPSIAAAA070AAPSIAAtk/lgAAPT/",
  "///uSQAAAPSIABzCyAMAAPSIAAAj+2YAAPSIAAAApt4DAPSIAAAAN/9XAPSIAAAAAMjMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJu1fXUdgoAAHzxTQs62WgAAN+JAAAAGE0AAOqHAAAAAAAA",
  "AIvxZxMAAAAAAAFiwvjWdgQAAAAAAAVP6ZoAAAAAAAAAd/QBAHQBAAAAePIBANiwKQpE6Z8AACyi4fbahAoAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqP////////+wAAAAOP9EAAAAAAAAOP9E",
  "AAAAAAAAOP9EAAAAAAAAOP9EAAAAAAAAOP9EAAAAAAAAOP9EAAAAAAAAOP9EAAAAAAAAOP9EAAAAAAAAOP9EAAAAAAAAOP9EAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOyQAAAAiPQAAOyQ",
  "AAAAiPQAAOyQAAAAiPQAAOyQAAAAiPQAAOyQAAAAiPQAAOyQAAAAiPQAAOuQAAAAiPMAAOWQAAAAiOwAAM+eAAAAltUAAH7wRwxD",
  "7oMAAAN02fbaeQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "b/4WAAAAEP12JP9YAAAAUf8rANqbAAAAlOEAAI/fAAAA2JYAAEX/IgAb/0wAAAbzZQBe9woAAACwqAChtwAAAABl6gHkbAAAAAAb",
  "/1j/IgAAAAAA0NrXAAAAAAAAhf+NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAA7X4AAAAAAHfzx50AAAAAAJXOobsAAAAAALOoe9kAYP9iANGCVfYAlu6ZAO9cLv8VzIfQDf81Cf469xn3Nf8P",
  "AOKJ0wDMhukAALzcmQCS2sMAAJb/XwBY/50AAG//JQAd/3cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHfSBAAAAPP9WAHT2HwACz7UAAATSqwBp9B8AAAA7/lPtcgAAAAAAnf3MAwAAAAAAbf+a",
  "AAAAAAAZ8K78MgAAAACs1wauxwEAAEz/QQAj+WMADOGjAAAAjesRj+8XAAAAEOyXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc/ojAAAAIPl5BdmqAAAApt0HAEv/OAAz/lAAAAC3xAC9vAAAAAAo",
  "+5j7KwAAAAAAkP+TAAAAAAAAPP9AAAAAAAAAPP9AAAAAAAAAPP9AAAAAAAAAPP9AAAAAAAAAPP9AAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALT///////9oAAAAAAAAnfwwAAAAAAA+/okA",
  "AAAAAAbX2ggAAAAAAID+PwAAAAAAJ/iYAAAAAAABwOQOAAAAAABj/00AAAAAABbtqAAAAAAAAKPsFgAAAAAAANz///////+QAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnP//gAAAAAAAnLwA",
  "AAAAAAAAnLwAAAAAAAAAnLwAAAAAAAAAnLwAAAAAAAAAnLwAAAAAAAAAnLwAAAAAAAAAnLwAAAAAAAAAnLwAAAAAAAAAnLwAAAAA",
  "AAAAnLwAAAAAAAAAnLwAAAAAAAAAnP//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEfJg",
  "AAAAAAAAAIjZAgAAAAAAABb2VgAAAAAAAACS0AAAAAAAAAAd+UwAAAAAAAAAnMcAAAAAAAAAJPxCAAAAAAAAAKa9AAAAAAAAACz+",
  "OAAAAAAAAACwswAAAAAAAAA1/i8AAAAAAAAAuqoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAB4//+kAAAAAAAAALSkAAAAAAAAALSkAAAAAAAAALSkAAAAAAAAALSkAAAAAAAAALSkAAAAAAAAALSkAAAAAAAA",
  "ALSkAAAAAAAAALSkAAAAAAAAALSkAAAAAAAAALSkAAAAAAAAALSkAAAAAAB4//+kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjP+SAAAAAABh9GzyaAAAAD3yRQBA8kMAIedQAAAASugmAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAA////////////AAAAAAAAAAAAAAAAAAAAAAAAAACP0AYAAAAAAAAEwIUAAAAAAAAAFt84AAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAt72PncdwEAAF+CHwg/8WcAAAAAAAAApbEAABeb4vv//74AALzJLgUAocAAAflgAAAB1MAAAM+1FRaN98AAACnA",
  "9emLm8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJjEAAAA",
  "AAAAAJjEAAAAAAAAAJjEAAAAAAAAAJjFivHvlAYAAJj+khE56oEAAJjyCQAAgO4AAJjQAAAAVP8TAJjPAAAAVf8SAJjyCQAAf+wA",
  "AJj+kxE46X8AAJjGi/LvlAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATmeb1wDkAAAbRzDMMN4UAAFj/JgAAAAAAAIroAAAAAAAAAIroAAAA",
  "AAAAAFj/JwAAAAAAAAbRzjQLNIIAAAATmeb2wDEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuKAAAAAAAAAAuKAAAAAAAAAAuKAAAAOM7POTu6AAAHXvQBGL/qAAAOKLAAAF7KAACf9g",
  "AAAAxaAACP5fAAAAxaAAAOGLAAAG7KAAAHfuPhCL/qAAAASO7fORu6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTzvjleQAAAFn/eRA76GIA",
  "ANu8AAAAdtkADv90AAAAQ/8JDv////////8hANtqAAAAAAAAAFrmSg0YWacAAABRyPfopywAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIXp/8gAAAAANv86AAAAAAAAXPkAAAAAAJT/////",
  "/8gAAAAAYPgAAAAAAAAAYPgAAAAAAAAAYPgAAAAAAAAAYPgAAAAAAAAAYPgAAAAAAAAAYPgAAAAAAAAAYPgAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAKJ7fObvKAAAHDwRBCG/aAAAN+NAAAF66AACP5gAAAAxKAACP5gAAAAxaAAAOCNAAAF66AAAHLwRA+G+qAAAAOL7vKV",
  "vJsAAAAAAAAA1noAACyQJg1q+CQAAAJt2vLHQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJTIAAAAAAAA",
  "AJTIAAAAAAAAAJTIAAAAAAAAAJTIeObxowgAAJT5hQ849mwAAJTrAwAAuKIAAJTLAAAAqLMAAJTIAAAAqLQAAJTIAAAAqLQAAJTI",
  "AAAAqLQAAJTIAAAAqLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAABP9UAAAAAAAABP9UAAAAAAAAAAAAAAAAACD///9UAAAAAAAABP9UAAAAAAAABP9UAAAAAAAABP9UAAAAAAAABP9UAAAA",
  "AAAABP9UAAAAAAAABP9UAAAAALT///////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAJzAAAAAAAAAAJzAAAAAAAAAAAAAAAAAAADs///AAAAAAAAAAJzAAAAAAAAAAJzAAAAAAAAAAJzA",
  "AAAAAAAAAJzAAAAAAAAAAJzAAAAAAAAAAJzAAAAAAAAAAJzAAAAAAAAAAKS0AAAAAAAAH+Z+AAAAAKT/86kNAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAET/IAAAAAAAAET/IAAAAAAAAET/IAAAAAAAAET/IAATzLgKAET/IBrVqQYAAET/",
  "Qd2bAgAAAET/8fxsAAAAAET/eGv4MwAAAET/IACu3A4AAET/IAAR4asAAET/IAAAOvtsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANT//7AAAAAAAAAArLAAAAAAAAAArLAAAAAAAAAArLAAAAAA",
  "AAAArLAAAAAAAAAArLAAAAAAAAAArLAAAAAAAAAArLAAAAAAAAAAobgAAAAAAAAAa/AmAAAAAAAABp3w/5QAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAANP+m8JKf8Z8ANP9IU/9vLP8mNP8LGP8wAPRGNP8EEP8oAOxPNP8EEP8oAOxQNP8EEP8oAOxQNP8EEP8oAOxQNP8EEP8oAOxQ",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAJTIeObxowgAAJT5hQ849mwAAJTrAwAAuKIAAJTLAAAAqLMAAJTIAAAAqLQAAJTIAAAAqLQAAJTIAAAA",
  "qLQAAJTIAAAAqLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABx3vrfdQAAAFz6Vg1T+GAAAMqpAAAAo9EAAO98AAAAdfYAAO98AAAAdvYAAMqo",
  "AAAAo9EAAF35VA1R+GIAAAB13/vheAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJzCjfLtjwQAAJz+jxE77HkAAJzwBwAAhOQAAJzMAAAAWP8K",
  "AJzLAAAAWf8MAJzwBwAAg+YAAJz+jxE56noAAJzCkPPvkgUAAJzAAAAAAAAAAJzAAAAAAAAAAJzAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB85/ahqLwAAF33Tg9z/rwAAMmlAAAA",
  "17wAAO97AAAArLwAAPB7AAAArbwAAMulAAAA17wAAGL3Sw5x/rwAAAGB6fajp7wAAAAAAAAAoLwAAAAAAAAAoLwAAAAAAAAAoLwA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABY/x+69MAcAABY",
  "/7BEDkZZAABY/1UAAAAAAABY/xYAAAAAAABY/wAAAAAAAABY/wAAAAAAAABY/wAAAAAAAABY/wAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AABm2PbVZAEAADf/Uwgnmh4AAFr9DQAAAAAAABLZ4JNfFgAAAAAGRH3R8S0AAAAAAAAF5X8AAGKCJwhL+U8AAA1+2fbWawAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2IAA",
  "AAAAAAAA2IAAAAAADP///////5AAAAAA2IAAAAAAAAAA2IAAAAAAAAAA2IAAAAAAAAAA2IAAAAAAAAAA0oUAAAAAAAAArMgVAAAA",
  "AAAAKsT0/5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJTIAAAAqLQAAJTIAAAAqLQAAJTIAAAAqLQAAJTIAAAAqLQAAJPIAAAArLQAAIPYAAAA",
  "0LQAAE7/Tgxq+LQAAAGR7e6Pq7QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGfxNAAAARv4eALmoAAAAob8AAFz2DQAJ8mIAAAvzXgBX9w4AAACi",
  "uQCyqAAAAABF/Cr6SwAAAAAC5dDqBAAAAAAAi/+SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4XAAAAAAAGnopKoAAAAAAKOrZ+QAM/82AN1t",
  "Kf8dd+J7Fv8wAOpXvFvBUPACAK6Z3gHblrUAAHH3oACZ93cAADP/WABQ/zoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMK2AQAAsscFABnoeABy",
  "7B0AAABB+HH4RwAAAAAAfv+FAAAAAAACufjAAwAAAACC5irjiQAAAEn7QQA7+lAAH+1/AAAAePAkAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEfdh",
  "AAAALP88AKLFAAAAj9cAADz/KQAF63IAAADVjQBT+RQAAABv6ga1qAAAAAAR92/8QgAAAAAAovnbAQAAAAAAPP94AAAAAAAAS/oY",
  "AAAAAAAUy6UAAAAAAKj7vhcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAFj//////6AAAAAAAAA6+V4AAAAAABzokQAAAAAACcy9BAAAAAAApt0TAAAAAAB48ywAAAAAAEb8UQAAAAAAAIT/",
  "/////6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGve",
  "+2gAAAAACPmJCQAAAAAAHv9EAAAAAAAAIP9AAAAAAAAAKf85AAAAAAAMivYRAAAAAGD/+1kAAAAAAAAOlO4JAAAAAAAALP80AAAA",
  "AAAAIP8/AAAAAAAAIP9AAAAAAAAAG/9HAAAAAAAABPSTCgAAAAAAAGDc+2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8k",
  "AAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAIP8kAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAGD73mgAAAAAAAAJhvgIAAAAAAAAPP8dAAAAAAAAOP8gAAAAAAAAMv8pAAAAAAAADfSLDAAAAAAA",
  "AFP5/2gAAAAABuqUDgAAAAAALP8sAAAAAAAAN/8gAAAAAAAAOP8gAAAAAAAAQP8bAAAAAAAKkPIDAAAAAGD73F4AAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "E6Ls6JMtEGNWTmESIXzc76ITAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "AAAAAAAAAAAAAAAAAAAA",
].join("");

const B64_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/** Decode a standard base64 string to raw bytes. Pure arithmetic — no atob, no
 *  Buffer, no image/font decoder — so the embedded atlas stays decode-free. */
function decodeBase64(b64: string): Uint8Array {
  const lut = new Int16Array(256).fill(-1);
  for (let i = 0; i < B64_ALPHABET.length; i++) lut[B64_ALPHABET.charCodeAt(i)] = i;
  const len = b64.length;
  let pad = 0;
  if (len > 0 && b64.charCodeAt(len - 1) === 61) pad++; // '='
  if (len > 1 && b64.charCodeAt(len - 2) === 61) pad++;
  const outLen = (len >> 2) * 3 - pad;
  const out = new Uint8Array(outLen);
  let o = 0;
  for (let i = 0; i < len; i += 4) {
    const a = lut[b64.charCodeAt(i)];
    const b = lut[b64.charCodeAt(i + 1)];
    const c = lut[b64.charCodeAt(i + 2)];
    const d = lut[b64.charCodeAt(i + 3)];
    const triple = (a << 18) | (b << 12) | ((c & 63) << 6) | (d & 63);
    if (o < outLen) out[o++] = (triple >> 16) & 0xff;
    if (o < outLen) out[o++] = (triple >> 8) & 0xff;
    if (o < outLen) out[o++] = triple & 0xff;
  }
  return out;
}

const ATLAS = decodeBase64(ATLAS_B64);

/** A single glyph: a view into the shared atlas (zero-copy). `alpha[y*width+x]`
 *  is the 8-bit coverage at cell pixel (x,y), top-left origin. */
export interface Glyph {
  /** cell width in source pixels */
  width: number;
  /** cell height in source pixels */
  height: number;
  /** horizontal advance in source pixels */
  advance: number;
  /** 8-bit alpha coverage, row-major, length width*height */
  alpha: Uint8Array;
}

/** True if `code` has a baked glyph (printable ASCII). */
export function isPrintable(code: number): boolean {
  return code >= FONT_FIRST_CODE && code <= FONT_LAST_CODE;
}

/** Glyph for an ASCII code point; out-of-range codes fall back to '?'. The
 *  returned `alpha` is a live view into the atlas — read-only, never mutate. */
export function glyphFor(code: number): Glyph {
  const c = isPrintable(code) ? code : FALLBACK_CODE;
  const off = (c - FONT_FIRST_CODE) * GLYPH_BYTES;
  return {
    width: GLYPH_W,
    height: GLYPH_H,
    advance: GLYPH_ADVANCE,
    alpha: ATLAS.subarray(off, off + GLYPH_BYTES),
  };
}
