#!/usr/bin/env node
// compile-vault.mjs — translate a design vault (a folder of .md documents) into the
// limina build, and write back the doc<->build link map.
//
//   node tools/design/compile-vault.mjs <vault-dir>
//
// Reads every *.md in the vault, runs it through the engine translator (vaultToStore ->
// compileDesignToGds) inside the limina binary, prints the compiled world, and writes
// <vault-dir>/build-map.md — the readable index linking each design entity to where it
// exists in the build (the "each document links to where it exists in the build" facet).

import { readdirSync, readFileSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const LIMINA_HOME = resolve(__dirname, "..", "..");
const LIMINA_BIN = process.env.LIMINA_BIN || join(LIMINA_HOME, "target", "release", "limina");

const vaultDir = resolve(process.argv[2] || process.cwd());
const docs = readdirSync(vaultDir)
  .filter((f) => f.endsWith(".md") && f !== "build-map.md")
  .map((f) => ({ name: f, content: readFileSync(join(vaultDir, f), "utf8") }));
if (docs.length === 0) { console.error(`no .md docs in ${vaultDir}`); process.exit(1); }

const BEGIN = "===VAULT_RESULT_BEGIN===";
const END = "===VAULT_RESULT_END===";
const harness = `
import { vaultToStore } from "${LIMINA_HOME}/js/src/game/design-vault.ts";
import { compileDesignToGds } from "${LIMINA_HOME}/js/src/game/design-compile.ts";
import { ops } from "${LIMINA_HOME}/js/src/engine.ts";
const docs = ${JSON.stringify(docs)};
const { store, links } = vaultToStore(docs);
const { gds, issues } = compileDesignToGds(store);
const placements = (gds && gds.world && gds.world.placements) ? gds.world.placements : [];
const has = (id) => placements.some((p) => p.id === id);
const entIds = new Set((gds ? gds.entities : []).map((e) => e.id));
const resolved = links.map((l) => {
  const loc = "location-" + l.entity, ent = "entity-" + l.entity;
  const buildId = has(loc) ? loc : has(ent) ? ent : entIds.has(l.entity) ? l.entity : null;
  return { ...l, buildId };
});
const out = {
  ok: !!gds,
  issues,
  placements: placements.map((p) => ({ id: p.id, entity: p.entity, position: p.transform.position })),
  entities: (gds ? gds.entities : []).map((e) => ({ id: e.id, role: e.role })),
  dod: (gds ? gds.dod : []).map((d) => ({ id: d.id, kind: d.kind })),
  links: resolved,
};
ops.op_log("${BEGIN}" + JSON.stringify(out) + "${END}");
`;

const tmp = mkdtempSync(join(tmpdir(), "limina-vault-"));
const harnessPath = join(tmp, "harness.ts");
writeFileSync(harnessPath, harness);
const res = spawnSync(LIMINA_BIN, [harnessPath], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
rmSync(tmp, { recursive: true, force: true });
const stdout = (res.stdout || "") + (res.stderr || "");
const m = stdout.match(new RegExp(BEGIN + "([\\s\\S]*?)" + END));
if (!m) {
  console.error("translator failed:\n" + stdout.slice(-2000));
  process.exit(1);
}
const r = JSON.parse(m[1]);
if (!r.ok) { console.error("compile issues:", JSON.stringify(r.issues, null, 2)); process.exit(1); }

// ---- report ----
console.log(`\n  Eastern Watch — vault compiled\n`);
console.log(`  placements: ${r.placements.length}   entities: ${r.entities.length}   dod: ${r.dod.length}`);
for (const p of r.placements) {
  console.log(`    ${p.id.padEnd(26)} @ [${p.position.map((n) => n.toFixed(0)).join(", ")}]`);
}
const built = r.links.filter((l) => l.buildId);
console.log(`\n  doc ↔ build links resolved: ${built.length}/${r.links.length}`);

// ---- write build-map.md (the doc <-> build index) ----
const rows = r.links.map((l) => {
  const src = l.doc === "worldBible" ? "world-bible" : l.doc;
  const where = l.buildId ? `\`${l.buildId}\`` : "_unbuilt_";
  return `| [[${src}#${l.name}\\|${l.name}]] | ${l.doc} | ${where} |`;
});
const map = `---
kind: build-map
generated: compile-vault
note: Auto-generated. Each design entity and where it exists in the limina build.
---

# Build Map

> Generated by \`compile-vault\`. This is the **doc ↔ build** index — every design
> entity from [[world-bible]] and [[cast]], and the build id it compiled into. Click a
> name to jump to the document that authored it; the build id is where it lives in the
> world log.

Compiled: **${r.placements.length} placements**, **${r.entities.length} entities**, **${built.length}/${r.links.length}** links resolved.

| Design entity | From | Build id |
| --- | --- | --- |
${rows.join("\n")}
`;
writeFileSync(join(vaultDir, "build-map.md"), map);
console.log(`\n  wrote ${join(vaultDir, "build-map.md")}\n`);
